// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

#include "config.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Nrmk {
namespace IndyFramework {
}  // namespace IndyFramework
}  // namespace Nrmk
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_config_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_config_2eproto = nullptr;
const ::uint32_t TableStruct_config_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_config_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\014config.proto\022\022Nrmk.IndyFramework\032\021conf"
    "ig_msgs.proto\032\021common_msgs.proto2\353M\n\006Con"
    "fig\022B\n\010GetNonce\022\031.Nrmk.IndyFramework.Emp"
    "ty\032\031.Nrmk.IndyFramework.Nonce\"\000\022C\n\005Login"
    "\022\032.Nrmk.IndyFramework.Digest\032\034.Nrmk.Indy"
    "Framework.LoginRes\"\000\022F\n\nTestDigest\022\032.Nrm"
    "k.IndyFramework.Passwd\032\032.Nrmk.IndyFramew"
    "ork.Digest\"\000\022H\n\013VerifyToken\022\031.Nrmk.IndyF"
    "ramework.Token\032\034.Nrmk.IndyFramework.Resp"
    "onse\"\000\022W\n\016ChangePassword\022%.Nrmk.IndyFram"
    "ework.ChangePasswordReq\032\034.Nrmk.IndyFrame"
    "work.Response\"\000\022L\n\rGetPathConfig\022\031.Nrmk."
    "IndyFramework.Empty\032\036.Nrmk.IndyFramework"
    ".PathConfig\"\000\022G\n\013SetLanguage\022\030.Nrmk.Indy"
    "Framework.Name\032\034.Nrmk.IndyFramework.Resp"
    "onse\"\000\022E\n\013GetRefFrame\022\031.Nrmk.IndyFramewo"
    "rk.Empty\032\031.Nrmk.IndyFramework.Frame\"\000\022F\n"
    "\016GetRefFrameFor\022\027.Nrmk.IndyFramework.Int"
    "\032\031.Nrmk.IndyFramework.Frame\"\000\022H\n\013SetRefF"
    "rame\022\031.Nrmk.IndyFramework.Frame\032\034.Nrmk.I"
    "ndyFramework.Response\"\000\022W\n\021SetRefFramePl"
    "anar\022\037.Nrmk.IndyFramework.PlanarFrame\032\037."
    "Nrmk.IndyFramework.FrameResult\"\000\022I\n\016SetL"
    "ockedJoint\022\027.Nrmk.IndyFramework.Int\032\034.Nr"
    "mk.IndyFramework.Response\"\000\022F\n\013SetToolLi"
    "nk\022\027.Nrmk.IndyFramework.Int\032\034.Nrmk.IndyF"
    "ramework.Response\"\000\022I\n\014SetToolFrame\022\031.Nr"
    "mk.IndyFramework.Frame\032\034.Nrmk.IndyFramew"
    "ork.Response\"\000\022J\n\rSetSpeedRatio\022\031.Nrmk.I"
    "ndyFramework.Ratio\032\034.Nrmk.IndyFramework."
    "Response\"\000\022G\n\rGetSpeedRatio\022\031.Nrmk.IndyF"
    "ramework.Empty\032\031.Nrmk.IndyFramework.Rati"
    "o\"\000\022S\n\017SetDIConfigList\022 .Nrmk.IndyFramew"
    "ork.DIConfigList\032\034.Nrmk.IndyFramework.Re"
    "sponse\"\000\022P\n\017GetDIConfigList\022\031.Nrmk.IndyF"
    "ramework.Empty\032 .Nrmk.IndyFramework.DICo"
    "nfigList\"\000\022S\n\017SetDOConfigList\022 .Nrmk.Ind"
    "yFramework.DOConfigList\032\034.Nrmk.IndyFrame"
    "work.Response\"\000\022P\n\017GetDOConfigList\022\031.Nrm"
    "k.IndyFramework.Empty\032 .Nrmk.IndyFramewo"
    "rk.DOConfigList\"\000\022O\n\017SetHomePosition\022\034.N"
    "rmk.IndyFramework.JointPos\032\034.Nrmk.IndyFr"
    "amework.Response\"\000\022L\n\017GetHomePosition\022\031."
    "Nrmk.IndyFramework.Empty\032\034.Nrmk.IndyFram"
    "ework.JointPos\"\000\022L\n\017GetPackPosition\022\031.Nr"
    "mk.IndyFramework.Empty\032\034.Nrmk.IndyFramew"
    "ork.JointPos\"\000\022L\n\021GetServoParamList\022\031.Nr"
    "mk.IndyFramework.Empty\032\032.Nrmk.IndyFramew"
    "ork.Vector\"\000\022K\n\013SetToolList\022\034.Nrmk.IndyF"
    "ramework.ToolList\032\034.Nrmk.IndyFramework.R"
    "esponse\"\000\022H\n\013GetToolList\022\031.Nrmk.IndyFram"
    "ework.Empty\032\034.Nrmk.IndyFramework.ToolLis"
    "t\"\000\022X\n\023GetVisionServerList\022\031.Nrmk.IndyFr"
    "amework.Empty\032$.Nrmk.IndyFramework.Visio"
    "nServerList\"\000\022[\n\023SetVisionServerList\022$.N"
    "rmk.IndyFramework.VisionServerList\032\034.Nrm"
    "k.IndyFramework.Response\"\000\022^\n\026GetSocketC"
    "ommandConfig\022\031.Nrmk.IndyFramework.Empty\032"
    "\'.Nrmk.IndyFramework.SocketCommandConfig"
    "\"\000\022a\n\026SetSocketCommandConfig\022\'.Nrmk.Indy"
    "Framework.SocketCommandConfig\032\034.Nrmk.Ind"
    "yFramework.Response\"\000\022X\n\023GetModbusServer"
    "List\022\031.Nrmk.IndyFramework.Empty\032$.Nrmk.I"
    "ndyFramework.ModbusServerList\"\000\022[\n\023SetMo"
    "dbusServerList\022$.Nrmk.IndyFramework.Modb"
    "usServerList\032\034.Nrmk.IndyFramework.Respon"
    "se\"\000\022P\n\017GetConveyorList\022\031.Nrmk.IndyFrame"
    "work.Empty\032 .Nrmk.IndyFramework.Conveyor"
    "List\"\000\022S\n\017SetConveyorList\022 .Nrmk.IndyFra"
    "mework.ConveyorList\032\034.Nrmk.IndyFramework"
    ".Response\"\000\022Y\n\017SetAutoServoOff\022&.Nrmk.In"
    "dyFramework.AutoServoOffConfig\032\034.Nrmk.In"
    "dyFramework.Response\"\000\022V\n\017GetAutoServoOf"
    "f\022\031.Nrmk.IndyFramework.Empty\032&.Nrmk.Indy"
    "Framework.AutoServoOffConfig\"\000\022W\n\023SetJoi"
    "ntControlGain\022 .Nrmk.IndyFramework.Joint"
    "GainSet\032\034.Nrmk.IndyFramework.Response\"\000\022"
    "T\n\023GetJointControlGain\022\031.Nrmk.IndyFramew"
    "ork.Empty\032 .Nrmk.IndyFramework.JointGain"
    "Set\"\000\022U\n\022SetTaskControlGain\022\037.Nrmk.IndyF"
    "ramework.TaskGainSet\032\034.Nrmk.IndyFramewor"
    "k.Response\"\000\022R\n\022GetTaskControlGain\022\031.Nrm"
    "k.IndyFramework.Empty\032\037.Nrmk.IndyFramewo"
    "rk.TaskGainSet\"\000\022_\n\027SetImpedanceControlG"
    "ain\022$.Nrmk.IndyFramework.ImpedanceGainSe"
    "t\032\034.Nrmk.IndyFramework.Response\"\000\022\\\n\027Get"
    "ImpedanceControlGain\022\031.Nrmk.IndyFramewor"
    "k.Empty\032$.Nrmk.IndyFramework.ImpedanceGa"
    "inSet\"\000\022W\n\023SetForceControlGain\022 .Nrmk.In"
    "dyFramework.ForceGainSet\032\034.Nrmk.IndyFram"
    "ework.Response\"\000\022T\n\023GetForceControlGain\022"
    "\031.Nrmk.IndyFramework.Empty\032 .Nrmk.IndyFr"
    "amework.ForceGainSet\"\000\022U\n\022SetTestControl"
    "Gain\022\037.Nrmk.IndyFramework.TestGainSet\032\034."
    "Nrmk.IndyFramework.Response\"\000\022R\n\022GetTest"
    "ControlGain\022\031.Nrmk.IndyFramework.Empty\032\037"
    ".Nrmk.IndyFramework.TestGainSet\"\000\022Y\n\024Set"
    "CustomControlGain\022!.Nrmk.IndyFramework.C"
    "ustomGainSet\032\034.Nrmk.IndyFramework.Respon"
    "se\"\000\022V\n\024GetCustomControlGain\022\031.Nrmk.Indy"
    "Framework.Empty\032!.Nrmk.IndyFramework.Cus"
    "tomGainSet\"\000\022V\n\031RestorFactoryControlGain"
    "s\022\031.Nrmk.IndyFramework.Empty\032\034.Nrmk.Indy"
    "Framework.Response\"\000\022g\n\031SetNewController"
    "TestOnOff\022*.Nrmk.IndyFramework.NewContro"
    "llerTestState\032\034.Nrmk.IndyFramework.Respo"
    "nse\"\000\022i\n\036GetNewControllerTestOnOffState\022"
    "\031.Nrmk.IndyFramework.Empty\032*.Nrmk.IndyFr"
    "amework.NewControllerTestState\"\000\022f\n\035SetC"
    "omplianceControlJointGain\022%.Nrmk.IndyFra"
    "mework.ComplianceGainSet\032\034.Nrmk.IndyFram"
    "ework.Response\"\000\022c\n\035GetComplianceControl"
    "JointGain\022\031.Nrmk.IndyFramework.Empty\032%.N"
    "rmk.IndyFramework.ComplianceGainSet\"\000\022V\n"
    "\017SetFrictionComp\022#.Nrmk.IndyFramework.Fr"
    "ictionCompSet\032\034.Nrmk.IndyFramework.Respo"
    "nse\"\000\022S\n\017GetFrictionComp\022\031.Nrmk.IndyFram"
    "ework.Empty\032#.Nrmk.IndyFramework.Frictio"
    "nCompSet\"\000\022Q\n\013SetMountPos\022\".Nrmk.IndyFra"
    "mework.MountingAngles\032\034.Nrmk.IndyFramewo"
    "rk.Response\"\000\022N\n\013GetMountPos\022\031.Nrmk.Indy"
    "Framework.Empty\032\".Nrmk.IndyFramework.Mou"
    "ntingAngles\"\000\022R\n\017GetIMUAutoMount\022\031.Nrmk."
    "IndyFramework.Empty\032\".Nrmk.IndyFramework"
    ".MountingAngles\"\000\022U\n\017SetToolProperty\022\".N"
    "rmk.IndyFramework.ToolProperties\032\034.Nrmk."
    "IndyFramework.Response\"\000\022R\n\017GetToolPrope"
    "rty\022\031.Nrmk.IndyFramework.Empty\032\".Nrmk.In"
    "dyFramework.ToolProperties\"\000\022R\n\021GetToolP"
    "ropertyAt\022\027.Nrmk.IndyFramework.Int\032\".Nrm"
    "k.IndyFramework.ToolProperties\"\000\022^\n\023SetT"
    "oolPropertyList\022\'.Nrmk.IndyFramework.Too"
    "lPropertyEntries\032\034.Nrmk.IndyFramework.Re"
    "sponse\"\000\022[\n\023GetToolPropertyList\022\031.Nrmk.I"
    "ndyFramework.Empty\032\'.Nrmk.IndyFramework."
    "ToolPropertyEntries\"\000\022R\n\020GetToolFrameLis"
    "t\022\031.Nrmk.IndyFramework.Empty\032!.Nrmk.Indy"
    "Framework.ToolFrameList\"\000\022U\n\020SetToolFram"
    "eList\022!.Nrmk.IndyFramework.ToolFrameList"
    "\032\034.Nrmk.IndyFramework.Response\"\000\022P\n\017GetR"
    "efFrameList\022\031.Nrmk.IndyFramework.Empty\032 "
    ".Nrmk.IndyFramework.RefFrameList\"\000\022S\n\017Se"
    "tRefFrameList\022 .Nrmk.IndyFramework.RefFr"
    "ameList\032\034.Nrmk.IndyFramework.Response\"\000\022"
    "R\n\020GetCustomPosList\022\031.Nrmk.IndyFramework"
    ".Empty\032!.Nrmk.IndyFramework.CustomPosLis"
    "t\"\000\022U\n\020SetCustomPosList\022!.Nrmk.IndyFrame"
    "work.CustomPosList\032\034.Nrmk.IndyFramework."
    "Response\"\000\022Z\n\020SetCollSensLevel\022&.Nrmk.In"
    "dyFramework.CollisionSensLevel\032\034.Nrmk.In"
    "dyFramework.Response\"\000\022W\n\020GetCollSensLev"
    "el\022\031.Nrmk.IndyFramework.Empty\032&.Nrmk.Ind"
    "yFramework.CollisionSensLevel\"\000\022[\n\020SetCo"
    "llSensParam\022\'.Nrmk.IndyFramework.Collisi"
    "onThresholds\032\034.Nrmk.IndyFramework.Respon"
    "se\"\000\022X\n\020GetCollSensParam\022\031.Nrmk.IndyFram"
    "ework.Empty\032\'.Nrmk.IndyFramework.Collisi"
    "onThresholds\"\000\022_\n\027GetDefaultCollSensPara"
    "m\022\031.Nrmk.IndyFramework.Empty\032\'.Nrmk.Indy"
    "Framework.CollisionThresholds\"\000\022T\n\rSetCo"
    "llPolicy\022#.Nrmk.IndyFramework.CollisionP"
    "olicy\032\034.Nrmk.IndyFramework.Response\"\000\022Q\n"
    "\rGetCollPolicy\022\031.Nrmk.IndyFramework.Empt"
    "y\032#.Nrmk.IndyFramework.CollisionPolicy\"\000"
    "\022c\n\027SetOnStartProgramConfig\022(.Nrmk.IndyF"
    "ramework.OnStartProgramConfig\032\034.Nrmk.Ind"
    "yFramework.Response\"\000\022`\n\027GetOnStartProgr"
    "amConfig\022\031.Nrmk.IndyFramework.Empty\032(.Nr"
    "mk.IndyFramework.OnStartProgramConfig\"\000\022"
    "S\n\026SetSimpleCollThreshold\022\031.Nrmk.IndyFra"
    "mework.Empty\032\034.Nrmk.IndyFramework.Respon"
    "se\"\000\022S\n\017SetSafetyLimits\022 .Nrmk.IndyFrame"
    "work.SafetyLimits\032\034.Nrmk.IndyFramework.R"
    "esponse\"\000\022P\n\017GetSafetyLimits\022\031.Nrmk.Indy"
    "Framework.Empty\032 .Nrmk.IndyFramework.Saf"
    "etyLimits\"\000\022X\n\023GetJointLimitConfig\022\031.Nrm"
    "k.IndyFramework.Empty\032$.Nrmk.IndyFramewo"
    "rk.JointLimitConfig\"\000\022[\n\023SetJointLimitCo"
    "nfig\022$.Nrmk.IndyFramework.JointLimitConf"
    "ig\032\034.Nrmk.IndyFramework.Response\"\000\022`\n\033Ge"
    "tOriginalJointLimitConfig\022\031.Nrmk.IndyFra"
    "mework.Empty\032$.Nrmk.IndyFramework.JointL"
    "imitConfig\"\000\022[\n\023SetSafetyStopConfig\022$.Nr"
    "mk.IndyFramework.SafetyStopConfig\032\034.Nrmk"
    ".IndyFramework.Response\"\000\022X\n\023GetSafetySt"
    "opConfig\022\031.Nrmk.IndyFramework.Empty\032$.Nr"
    "mk.IndyFramework.SafetyStopConfig\"\000\022i\n\022S"
    "aveSafetySnapshot\022).Nrmk.IndyFramework.S"
    "aveSafetySnapshotReq\032&.Nrmk.IndyFramewor"
    "k.SafetySnapshotInfo\"\000\022Z\n\023ListSafetySnap"
    "shots\022\031.Nrmk.IndyFramework.Empty\032&.Nrmk."
    "IndyFramework.SafetySnapshotList\"\000\022]\n\025Re"
    "storeSafetySnapshot\022$.Nrmk.IndyFramework"
    ".SafetySnapshotId\032\034.Nrmk.IndyFramework.R"
    "esponse\"\000\022\\\n\024DeleteSafetySnapshot\022$.Nrmk"
    ".IndyFramework.SafetySnapshotId\032\034.Nrmk.I"
    "ndyFramework.Response\"\000\022V\n\031RestorFactory"
    "SafetyConfig\022\031.Nrmk.IndyFramework.Empty\032"
    "\034.Nrmk.IndyFramework.Response\"\000\022V\n\017GetRe"
    "ducedRatio\022\031.Nrmk.IndyFramework.Empty\032&."
    "Nrmk.IndyFramework.GetReducedRatioRes\"\000\022"
    "V\n\017GetReducedSpeed\022\031.Nrmk.IndyFramework."
    "Empty\032&.Nrmk.IndyFramework.GetReducedSpe"
    "edRes\"\000\022Y\n\017SetReducedSpeed\022&.Nrmk.IndyFr"
    "amework.SetReducedSpeedReq\032\034.Nrmk.IndyFr"
    "amework.Response\"\000\022W\n\021SetFTSensorConfig\022"
    "\".Nrmk.IndyFramework.FTSensorDevice\032\034.Nr"
    "mk.IndyFramework.Response\"\000\022T\n\021GetFTSens"
    "orConfig\022\031.Nrmk.IndyFramework.Empty\032\".Nr"
    "mk.IndyFramework.FTSensorDevice\"\000\022U\n\024Get"
    "FTSensorConfigFor\022\027.Nrmk.IndyFramework.I"
    "nt\032\".Nrmk.IndyFramework.FTSensorDevice\"\000"
    "\022S\n\017SetTeleOpParams\022 .Nrmk.IndyFramework"
    ".TeleOpParams\032\034.Nrmk.IndyFramework.Respo"
    "nse\"\000\022P\n\017GetTeleOpParams\022\031.Nrmk.IndyFram"
    "ework.Empty\032 .Nrmk.IndyFramework.TeleOpP"
    "arams\"\000\022X\n\023GetKinematicsParams\022\031.Nrmk.In"
    "dyFramework.Empty\032$.Nrmk.IndyFramework.K"
    "inematicsParams\"\000\022_\n\026GetCollisonModelMar"
    "gin\022\031.Nrmk.IndyFramework.Empty\032(.Nrmk.In"
    "dyFramework.CollisionModelMargin\"\000\022b\n\026Se"
    "tCollisonModelMargin\022(.Nrmk.IndyFramewor"
    "k.CollisionModelMargin\032\034.Nrmk.IndyFramew"
    "ork.Response\"\000\022U\n\020SetToolShapeList\022!.Nrm"
    "k.IndyFramework.ToolShapeList\032\034.Nrmk.Ind"
    "yFramework.Response\"\000\022R\n\020GetToolShapeLis"
    "t\022\031.Nrmk.IndyFramework.Empty\032!.Nrmk.Indy"
    "Framework.ToolShapeList\"\000\022Y\n\022SetEnvironm"
    "entList\022#.Nrmk.IndyFramework.Environment"
    "List\032\034.Nrmk.IndyFramework.Response\"\000\022V\n\022"
    "GetEnvironmentList\022\031.Nrmk.IndyFramework."
    "Empty\032#.Nrmk.IndyFramework.EnvironmentLi"
    "st\"\000\022[\n\023SetSensorlessParams\022$.Nrmk.IndyF"
    "ramework.SensorlessParams\032\034.Nrmk.IndyFra"
    "mework.Response\"\000\022X\n\023GetSensorlessParams"
    "\022\031.Nrmk.IndyFramework.Empty\032$.Nrmk.IndyF"
    "ramework.SensorlessParams\"\000\022]\n\027GetWeldin"
    "gMachineConfig\022\031.Nrmk.IndyFramework.Empt"
    "y\032%.Nrmk.IndyFramework.WeldingConfigInfo"
    "\"\000\022`\n\027SetWeldingMachineConfig\022%.Nrmk.Ind"
    "yFramework.WeldingConfigInfo\032\034.Nrmk.Indy"
    "Framework.Response\"\000\022X\n\023GetWeldPositionL"
    "ist\022\031.Nrmk.IndyFramework.Empty\032$.Nrmk.In"
    "dyFramework.WeldPositionList\"\000\022[\n\023SetWel"
    "dPositionList\022$.Nrmk.IndyFramework.WeldP"
    "ositionList\032\034.Nrmk.IndyFramework.Respons"
    "e\"\000\022a\n\026SetOperationModeConfig\022\'.Nrmk.Ind"
    "yFramework.OperationModeConfig\032\034.Nrmk.In"
    "dyFramework.Response\"\000\022^\n\026GetOperationMo"
    "deConfig\022\031.Nrmk.IndyFramework.Empty\032\'.Nr"
    "mk.IndyFramework.OperationModeConfig\"\000b\006"
    "proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_config_2eproto_deps[2] =
    {
        &::descriptor_table_common_5fmsgs_2eproto,
        &::descriptor_table_config_5fmsgs_2eproto,
};
static ::absl::once_flag descriptor_table_config_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_config_2eproto = {
    false,
    false,
    10046,
    descriptor_table_protodef_config_2eproto,
    "config.proto",
    &descriptor_table_config_2eproto_once,
    descriptor_table_config_2eproto_deps,
    2,
    0,
    schemas,
    file_default_instances,
    TableStruct_config_2eproto::offsets,
    nullptr,
    file_level_enum_descriptors_config_2eproto,
    file_level_service_descriptors_config_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_config_2eproto_getter() {
  return &descriptor_table_config_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_config_2eproto(&descriptor_table_config_2eproto);
namespace Nrmk {
namespace IndyFramework {
// @@protoc_insertion_point(namespace_scope)
}  // namespace IndyFramework
}  // namespace Nrmk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
