// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

#include "config.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Nrmk {
namespace IndyFramework {
}  // namespace IndyFramework
}  // namespace Nrmk
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_config_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_config_2eproto = nullptr;
const ::uint32_t TableStruct_config_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_config_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\014config.proto\022\022Nrmk.IndyFramework\032\021conf"
    "ig_msgs.proto\032\021common_msgs.proto2\370=\n\006Con"
    "fig\022B\n\010GetNonce\022\031.Nrmk.IndyFramework.Emp"
    "ty\032\031.Nrmk.IndyFramework.Nonce\"\000\022C\n\005Login"
    "\022\032.Nrmk.IndyFramework.Digest\032\034.Nrmk.Indy"
    "Framework.LoginRes\"\000\022F\n\nTestDigest\022\032.Nrm"
    "k.IndyFramework.Passwd\032\032.Nrmk.IndyFramew"
    "ork.Digest\"\000\022H\n\013VerifyToken\022\031.Nrmk.IndyF"
    "ramework.Token\032\034.Nrmk.IndyFramework.Resp"
    "onse\"\000\022W\n\016ChangePassword\022%.Nrmk.IndyFram"
    "ework.ChangePasswordReq\032\034.Nrmk.IndyFrame"
    "work.Response\"\000\022L\n\rGetPathConfig\022\031.Nrmk."
    "IndyFramework.Empty\032\036.Nrmk.IndyFramework"
    ".PathConfig\"\000\022E\n\013GetRefFrame\022\031.Nrmk.Indy"
    "Framework.Empty\032\031.Nrmk.IndyFramework.Fra"
    "me\"\000\022F\n\016GetRefFrameFor\022\027.Nrmk.IndyFramew"
    "ork.Int\032\031.Nrmk.IndyFramework.Frame\"\000\022H\n\013"
    "SetRefFrame\022\031.Nrmk.IndyFramework.Frame\032\034"
    ".Nrmk.IndyFramework.Response\"\000\022W\n\021SetRef"
    "FramePlanar\022\037.Nrmk.IndyFramework.PlanarF"
    "rame\032\037.Nrmk.IndyFramework.FrameResult\"\000\022"
    "I\n\016SetLockedJoint\022\027.Nrmk.IndyFramework.I"
    "nt\032\034.Nrmk.IndyFramework.Response\"\000\022F\n\013Se"
    "tToolLink\022\027.Nrmk.IndyFramework.Int\032\034.Nrm"
    "k.IndyFramework.Response\"\000\022I\n\014SetToolFra"
    "me\022\031.Nrmk.IndyFramework.Frame\032\034.Nrmk.Ind"
    "yFramework.Response\"\000\022J\n\rSetSpeedRatio\022\031"
    ".Nrmk.IndyFramework.Ratio\032\034.Nrmk.IndyFra"
    "mework.Response\"\000\022G\n\rGetSpeedRatio\022\031.Nrm"
    "k.IndyFramework.Empty\032\031.Nrmk.IndyFramewo"
    "rk.Ratio\"\000\022S\n\017SetDIConfigList\022 .Nrmk.Ind"
    "yFramework.DIConfigList\032\034.Nrmk.IndyFrame"
    "work.Response\"\000\022P\n\017GetDIConfigList\022\031.Nrm"
    "k.IndyFramework.Empty\032 .Nrmk.IndyFramewo"
    "rk.DIConfigList\"\000\022S\n\017SetDOConfigList\022 .N"
    "rmk.IndyFramework.DOConfigList\032\034.Nrmk.In"
    "dyFramework.Response\"\000\022P\n\017GetDOConfigLis"
    "t\022\031.Nrmk.IndyFramework.Empty\032 .Nrmk.Indy"
    "Framework.DOConfigList\"\000\022O\n\017SetHomePosit"
    "ion\022\034.Nrmk.IndyFramework.JointPos\032\034.Nrmk"
    ".IndyFramework.Response\"\000\022L\n\017GetHomePosi"
    "tion\022\031.Nrmk.IndyFramework.Empty\032\034.Nrmk.I"
    "ndyFramework.JointPos\"\000\022L\n\017GetPackPositi"
    "on\022\031.Nrmk.IndyFramework.Empty\032\034.Nrmk.Ind"
    "yFramework.JointPos\"\000\022K\n\013SetToolList\022\034.N"
    "rmk.IndyFramework.ToolList\032\034.Nrmk.IndyFr"
    "amework.Response\"\000\022H\n\013GetToolList\022\031.Nrmk"
    ".IndyFramework.Empty\032\034.Nrmk.IndyFramewor"
    "k.ToolList\"\000\022X\n\023GetVisionServerList\022\031.Nr"
    "mk.IndyFramework.Empty\032$.Nrmk.IndyFramew"
    "ork.VisionServerList\"\000\022[\n\023SetVisionServe"
    "rList\022$.Nrmk.IndyFramework.VisionServerL"
    "ist\032\034.Nrmk.IndyFramework.Response\"\000\022X\n\023G"
    "etModbusServerList\022\031.Nrmk.IndyFramework."
    "Empty\032$.Nrmk.IndyFramework.ModbusServerL"
    "ist\"\000\022[\n\023SetModbusServerList\022$.Nrmk.Indy"
    "Framework.ModbusServerList\032\034.Nrmk.IndyFr"
    "amework.Response\"\000\022P\n\017GetConveyorList\022\031."
    "Nrmk.IndyFramework.Empty\032 .Nrmk.IndyFram"
    "ework.ConveyorList\"\000\022S\n\017SetConveyorList\022"
    " .Nrmk.IndyFramework.ConveyorList\032\034.Nrmk"
    ".IndyFramework.Response\"\000\022Y\n\017SetAutoServ"
    "oOff\022&.Nrmk.IndyFramework.AutoServoOffCo"
    "nfig\032\034.Nrmk.IndyFramework.Response\"\000\022V\n\017"
    "GetAutoServoOff\022\031.Nrmk.IndyFramework.Emp"
    "ty\032&.Nrmk.IndyFramework.AutoServoOffConf"
    "ig\"\000\022W\n\023SetJointControlGain\022 .Nrmk.IndyF"
    "ramework.JointGainSet\032\034.Nrmk.IndyFramewo"
    "rk.Response\"\000\022T\n\023GetJointControlGain\022\031.N"
    "rmk.IndyFramework.Empty\032 .Nrmk.IndyFrame"
    "work.JointGainSet\"\000\022U\n\022SetTaskControlGai"
    "n\022\037.Nrmk.IndyFramework.TaskGainSet\032\034.Nrm"
    "k.IndyFramework.Response\"\000\022R\n\022GetTaskCon"
    "trolGain\022\031.Nrmk.IndyFramework.Empty\032\037.Nr"
    "mk.IndyFramework.TaskGainSet\"\000\022_\n\027SetImp"
    "edanceControlGain\022$.Nrmk.IndyFramework.I"
    "mpedanceGainSet\032\034.Nrmk.IndyFramework.Res"
    "ponse\"\000\022\\\n\027GetImpedanceControlGain\022\031.Nrm"
    "k.IndyFramework.Empty\032$.Nrmk.IndyFramewo"
    "rk.ImpedanceGainSet\"\000\022W\n\023SetForceControl"
    "Gain\022 .Nrmk.IndyFramework.ForceGainSet\032\034"
    ".Nrmk.IndyFramework.Response\"\000\022T\n\023GetFor"
    "ceControlGain\022\031.Nrmk.IndyFramework.Empty"
    "\032 .Nrmk.IndyFramework.ForceGainSet\"\000\022U\n\022"
    "SetTestControlGain\022\037.Nrmk.IndyFramework."
    "TestGainSet\032\034.Nrmk.IndyFramework.Respons"
    "e\"\000\022R\n\022GetTestControlGain\022\031.Nrmk.IndyFra"
    "mework.Empty\032\037.Nrmk.IndyFramework.TestGa"
    "inSet\"\000\022Y\n\024SetCustomControlGain\022!.Nrmk.I"
    "ndyFramework.CustomGainSet\032\034.Nrmk.IndyFr"
    "amework.Response\"\000\022V\n\024GetCustomControlGa"
    "in\022\031.Nrmk.IndyFramework.Empty\032!.Nrmk.Ind"
    "yFramework.CustomGainSet\"\000\022g\n\031SetNewCont"
    "rollerTestOnOff\022*.Nrmk.IndyFramework.New"
    "ControllerTestState\032\034.Nrmk.IndyFramework"
    ".Response\"\000\022i\n\036GetNewControllerTestOnOff"
    "State\022\031.Nrmk.IndyFramework.Empty\032*.Nrmk."
    "IndyFramework.NewControllerTestState\"\000\022f"
    "\n\035SetComplianceControlJointGain\022%.Nrmk.I"
    "ndyFramework.ComplianceGainSet\032\034.Nrmk.In"
    "dyFramework.Response\"\000\022c\n\035GetComplianceC"
    "ontrolJointGain\022\031.Nrmk.IndyFramework.Emp"
    "ty\032%.Nrmk.IndyFramework.ComplianceGainSe"
    "t\"\000\022V\n\017SetFrictionComp\022#.Nrmk.IndyFramew"
    "ork.FrictionCompSet\032\034.Nrmk.IndyFramework"
    ".Response\"\000\022S\n\017GetFrictionComp\022\031.Nrmk.In"
    "dyFramework.Empty\032#.Nrmk.IndyFramework.F"
    "rictionCompSet\"\000\022Q\n\013SetMountPos\022\".Nrmk.I"
    "ndyFramework.MountingAngles\032\034.Nrmk.IndyF"
    "ramework.Response\"\000\022N\n\013GetMountPos\022\031.Nrm"
    "k.IndyFramework.Empty\032\".Nrmk.IndyFramewo"
    "rk.MountingAngles\"\000\022U\n\017SetToolProperty\022\""
    ".Nrmk.IndyFramework.ToolProperties\032\034.Nrm"
    "k.IndyFramework.Response\"\000\022R\n\017GetToolPro"
    "perty\022\031.Nrmk.IndyFramework.Empty\032\".Nrmk."
    "IndyFramework.ToolProperties\"\000\022R\n\021GetToo"
    "lPropertyAt\022\027.Nrmk.IndyFramework.Int\032\".N"
    "rmk.IndyFramework.ToolProperties\"\000\022R\n\020Ge"
    "tToolFrameList\022\031.Nrmk.IndyFramework.Empt"
    "y\032!.Nrmk.IndyFramework.ToolFrameList\"\000\022U"
    "\n\020SetToolFrameList\022!.Nrmk.IndyFramework."
    "ToolFrameList\032\034.Nrmk.IndyFramework.Respo"
    "nse\"\000\022P\n\017GetRefFrameList\022\031.Nrmk.IndyFram"
    "ework.Empty\032 .Nrmk.IndyFramework.RefFram"
    "eList\"\000\022S\n\017SetRefFrameList\022 .Nrmk.IndyFr"
    "amework.RefFrameList\032\034.Nrmk.IndyFramewor"
    "k.Response\"\000\022R\n\020GetCustomPosList\022\031.Nrmk."
    "IndyFramework.Empty\032!.Nrmk.IndyFramework"
    ".CustomPosList\"\000\022U\n\020SetCustomPosList\022!.N"
    "rmk.IndyFramework.CustomPosList\032\034.Nrmk.I"
    "ndyFramework.Response\"\000\022Z\n\020SetCollSensLe"
    "vel\022&.Nrmk.IndyFramework.CollisionSensLe"
    "vel\032\034.Nrmk.IndyFramework.Response\"\000\022W\n\020G"
    "etCollSensLevel\022\031.Nrmk.IndyFramework.Emp"
    "ty\032&.Nrmk.IndyFramework.CollisionSensLev"
    "el\"\000\022[\n\020SetCollSensParam\022\'.Nrmk.IndyFram"
    "ework.CollisionThresholds\032\034.Nrmk.IndyFra"
    "mework.Response\"\000\022X\n\020GetCollSensParam\022\031."
    "Nrmk.IndyFramework.Empty\032\'.Nrmk.IndyFram"
    "ework.CollisionThresholds\"\000\022_\n\027GetDefaul"
    "tCollSensParam\022\031.Nrmk.IndyFramework.Empt"
    "y\032\'.Nrmk.IndyFramework.CollisionThreshol"
    "ds\"\000\022T\n\rSetCollPolicy\022#.Nrmk.IndyFramewo"
    "rk.CollisionPolicy\032\034.Nrmk.IndyFramework."
    "Response\"\000\022Q\n\rGetCollPolicy\022\031.Nrmk.IndyF"
    "ramework.Empty\032#.Nrmk.IndyFramework.Coll"
    "isionPolicy\"\000\022c\n\027SetOnStartProgramConfig"
    "\022(.Nrmk.IndyFramework.OnStartProgramConf"
    "ig\032\034.Nrmk.IndyFramework.Response\"\000\022`\n\027Ge"
    "tOnStartProgramConfig\022\031.Nrmk.IndyFramewo"
    "rk.Empty\032(.Nrmk.IndyFramework.OnStartPro"
    "gramConfig\"\000\022S\n\026SetSimpleCollThreshold\022\031"
    ".Nrmk.IndyFramework.Empty\032\034.Nrmk.IndyFra"
    "mework.Response\"\000\022S\n\017SetSafetyLimits\022 .N"
    "rmk.IndyFramework.SafetyLimits\032\034.Nrmk.In"
    "dyFramework.Response\"\000\022P\n\017GetSafetyLimit"
    "s\022\031.Nrmk.IndyFramework.Empty\032 .Nrmk.Indy"
    "Framework.SafetyLimits\"\000\022[\n\023SetSafetySto"
    "pConfig\022$.Nrmk.IndyFramework.SafetyStopC"
    "onfig\032\034.Nrmk.IndyFramework.Response\"\000\022X\n"
    "\023GetSafetyStopConfig\022\031.Nrmk.IndyFramewor"
    "k.Empty\032$.Nrmk.IndyFramework.SafetyStopC"
    "onfig\"\000\022V\n\017GetReducedRatio\022\031.Nrmk.IndyFr"
    "amework.Empty\032&.Nrmk.IndyFramework.GetRe"
    "ducedRatioRes\"\000\022V\n\017GetReducedSpeed\022\031.Nrm"
    "k.IndyFramework.Empty\032&.Nrmk.IndyFramewo"
    "rk.GetReducedSpeedRes\"\000\022Y\n\017SetReducedSpe"
    "ed\022&.Nrmk.IndyFramework.SetReducedSpeedR"
    "eq\032\034.Nrmk.IndyFramework.Response\"\000\022W\n\021Se"
    "tFTSensorConfig\022\".Nrmk.IndyFramework.FTS"
    "ensorDevice\032\034.Nrmk.IndyFramework.Respons"
    "e\"\000\022T\n\021GetFTSensorConfig\022\031.Nrmk.IndyFram"
    "ework.Empty\032\".Nrmk.IndyFramework.FTSenso"
    "rDevice\"\000\022U\n\024GetFTSensorConfigFor\022\027.Nrmk"
    ".IndyFramework.Int\032\".Nrmk.IndyFramework."
    "FTSensorDevice\"\000\022S\n\017SetTeleOpParams\022 .Nr"
    "mk.IndyFramework.TeleOpParams\032\034.Nrmk.Ind"
    "yFramework.Response\"\000\022P\n\017GetTeleOpParams"
    "\022\031.Nrmk.IndyFramework.Empty\032 .Nrmk.IndyF"
    "ramework.TeleOpParams\"\000\022X\n\023GetKinematics"
    "Params\022\031.Nrmk.IndyFramework.Empty\032$.Nrmk"
    ".IndyFramework.KinematicsParams\"\000\022_\n\026Get"
    "CollisonModelMargin\022\031.Nrmk.IndyFramework"
    ".Empty\032(.Nrmk.IndyFramework.CollisionMod"
    "elMargin\"\000\022b\n\026SetCollisonModelMargin\022(.N"
    "rmk.IndyFramework.CollisionModelMargin\032\034"
    ".Nrmk.IndyFramework.Response\"\000\022U\n\020SetToo"
    "lShapeList\022!.Nrmk.IndyFramework.ToolShap"
    "eList\032\034.Nrmk.IndyFramework.Response\"\000\022R\n"
    "\020GetToolShapeList\022\031.Nrmk.IndyFramework.E"
    "mpty\032!.Nrmk.IndyFramework.ToolShapeList\""
    "\000\022Y\n\022SetEnvironmentList\022#.Nrmk.IndyFrame"
    "work.EnvironmentList\032\034.Nrmk.IndyFramewor"
    "k.Response\"\000\022V\n\022GetEnvironmentList\022\031.Nrm"
    "k.IndyFramework.Empty\032#.Nrmk.IndyFramewo"
    "rk.EnvironmentList\"\000\022[\n\023SetSensorlessPar"
    "ams\022$.Nrmk.IndyFramework.SensorlessParam"
    "s\032\034.Nrmk.IndyFramework.Response\"\000\022X\n\023Get"
    "SensorlessParams\022\031.Nrmk.IndyFramework.Em"
    "pty\032$.Nrmk.IndyFramework.SensorlessParam"
    "s\"\000b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_config_2eproto_deps[2] =
    {
        &::descriptor_table_common_5fmsgs_2eproto,
        &::descriptor_table_config_5fmsgs_2eproto,
};
static ::absl::once_flag descriptor_table_config_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_config_2eproto = {
    false,
    false,
    8011,
    descriptor_table_protodef_config_2eproto,
    "config.proto",
    &descriptor_table_config_2eproto_once,
    descriptor_table_config_2eproto_deps,
    2,
    0,
    schemas,
    file_default_instances,
    TableStruct_config_2eproto::offsets,
    nullptr,
    file_level_enum_descriptors_config_2eproto,
    file_level_service_descriptors_config_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_config_2eproto_getter() {
  return &descriptor_table_config_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_config_2eproto(&descriptor_table_config_2eproto);
namespace Nrmk {
namespace IndyFramework {
// @@protoc_insertion_point(namespace_scope)
}  // namespace IndyFramework
}  // namespace Nrmk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
