// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

#include "config.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Nrmk {
namespace IndyFramework {
}  // namespace IndyFramework
}  // namespace Nrmk
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_config_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_config_2eproto = nullptr;
const ::uint32_t TableStruct_config_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_config_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\014config.proto\022\022Nrmk.IndyFramework\032\021conf"
    "ig_msgs.proto\032\021common_msgs.proto2\221K\n\006Con"
    "fig\022B\n\010GetNonce\022\031.Nrmk.IndyFramework.Emp"
    "ty\032\031.Nrmk.IndyFramework.Nonce\"\000\022C\n\005Login"
    "\022\032.Nrmk.IndyFramework.Digest\032\034.Nrmk.Indy"
    "Framework.LoginRes\"\000\022F\n\nTestDigest\022\032.Nrm"
    "k.IndyFramework.Passwd\032\032.Nrmk.IndyFramew"
    "ork.Digest\"\000\022H\n\013VerifyToken\022\031.Nrmk.IndyF"
    "ramework.Token\032\034.Nrmk.IndyFramework.Resp"
    "onse\"\000\022W\n\016ChangePassword\022%.Nrmk.IndyFram"
    "ework.ChangePasswordReq\032\034.Nrmk.IndyFrame"
    "work.Response\"\000\022L\n\rGetPathConfig\022\031.Nrmk."
    "IndyFramework.Empty\032\036.Nrmk.IndyFramework"
    ".PathConfig\"\000\022E\n\013GetRefFrame\022\031.Nrmk.Indy"
    "Framework.Empty\032\031.Nrmk.IndyFramework.Fra"
    "me\"\000\022F\n\016GetRefFrameFor\022\027.Nrmk.IndyFramew"
    "ork.Int\032\031.Nrmk.IndyFramework.Frame\"\000\022H\n\013"
    "SetRefFrame\022\031.Nrmk.IndyFramework.Frame\032\034"
    ".Nrmk.IndyFramework.Response\"\000\022W\n\021SetRef"
    "FramePlanar\022\037.Nrmk.IndyFramework.PlanarF"
    "rame\032\037.Nrmk.IndyFramework.FrameResult\"\000\022"
    "I\n\016SetLockedJoint\022\027.Nrmk.IndyFramework.I"
    "nt\032\034.Nrmk.IndyFramework.Response\"\000\022F\n\013Se"
    "tToolLink\022\027.Nrmk.IndyFramework.Int\032\034.Nrm"
    "k.IndyFramework.Response\"\000\022I\n\014SetToolFra"
    "me\022\031.Nrmk.IndyFramework.Frame\032\034.Nrmk.Ind"
    "yFramework.Response\"\000\022J\n\rSetSpeedRatio\022\031"
    ".Nrmk.IndyFramework.Ratio\032\034.Nrmk.IndyFra"
    "mework.Response\"\000\022G\n\rGetSpeedRatio\022\031.Nrm"
    "k.IndyFramework.Empty\032\031.Nrmk.IndyFramewo"
    "rk.Ratio\"\000\022S\n\017SetDIConfigList\022 .Nrmk.Ind"
    "yFramework.DIConfigList\032\034.Nrmk.IndyFrame"
    "work.Response\"\000\022P\n\017GetDIConfigList\022\031.Nrm"
    "k.IndyFramework.Empty\032 .Nrmk.IndyFramewo"
    "rk.DIConfigList\"\000\022S\n\017SetDOConfigList\022 .N"
    "rmk.IndyFramework.DOConfigList\032\034.Nrmk.In"
    "dyFramework.Response\"\000\022P\n\017GetDOConfigLis"
    "t\022\031.Nrmk.IndyFramework.Empty\032 .Nrmk.Indy"
    "Framework.DOConfigList\"\000\022O\n\017SetHomePosit"
    "ion\022\034.Nrmk.IndyFramework.JointPos\032\034.Nrmk"
    ".IndyFramework.Response\"\000\022L\n\017GetHomePosi"
    "tion\022\031.Nrmk.IndyFramework.Empty\032\034.Nrmk.I"
    "ndyFramework.JointPos\"\000\022L\n\017GetPackPositi"
    "on\022\031.Nrmk.IndyFramework.Empty\032\034.Nrmk.Ind"
    "yFramework.JointPos\"\000\022K\n\013SetToolList\022\034.N"
    "rmk.IndyFramework.ToolList\032\034.Nrmk.IndyFr"
    "amework.Response\"\000\022H\n\013GetToolList\022\031.Nrmk"
    ".IndyFramework.Empty\032\034.Nrmk.IndyFramewor"
    "k.ToolList\"\000\022X\n\023GetVisionServerList\022\031.Nr"
    "mk.IndyFramework.Empty\032$.Nrmk.IndyFramew"
    "ork.VisionServerList\"\000\022[\n\023SetVisionServe"
    "rList\022$.Nrmk.IndyFramework.VisionServerL"
    "ist\032\034.Nrmk.IndyFramework.Response\"\000\022X\n\023G"
    "etModbusServerList\022\031.Nrmk.IndyFramework."
    "Empty\032$.Nrmk.IndyFramework.ModbusServerL"
    "ist\"\000\022[\n\023SetModbusServerList\022$.Nrmk.Indy"
    "Framework.ModbusServerList\032\034.Nrmk.IndyFr"
    "amework.Response\"\000\022P\n\017GetConveyorList\022\031."
    "Nrmk.IndyFramework.Empty\032 .Nrmk.IndyFram"
    "ework.ConveyorList\"\000\022S\n\017SetConveyorList\022"
    " .Nrmk.IndyFramework.ConveyorList\032\034.Nrmk"
    ".IndyFramework.Response\"\000\022Y\n\017SetAutoServ"
    "oOff\022&.Nrmk.IndyFramework.AutoServoOffCo"
    "nfig\032\034.Nrmk.IndyFramework.Response\"\000\022V\n\017"
    "GetAutoServoOff\022\031.Nrmk.IndyFramework.Emp"
    "ty\032&.Nrmk.IndyFramework.AutoServoOffConf"
    "ig\"\000\022W\n\023SetJointControlGain\022 .Nrmk.IndyF"
    "ramework.JointGainSet\032\034.Nrmk.IndyFramewo"
    "rk.Response\"\000\022T\n\023GetJointControlGain\022\031.N"
    "rmk.IndyFramework.Empty\032 .Nrmk.IndyFrame"
    "work.JointGainSet\"\000\022U\n\022SetTaskControlGai"
    "n\022\037.Nrmk.IndyFramework.TaskGainSet\032\034.Nrm"
    "k.IndyFramework.Response\"\000\022R\n\022GetTaskCon"
    "trolGain\022\031.Nrmk.IndyFramework.Empty\032\037.Nr"
    "mk.IndyFramework.TaskGainSet\"\000\022_\n\027SetImp"
    "edanceControlGain\022$.Nrmk.IndyFramework.I"
    "mpedanceGainSet\032\034.Nrmk.IndyFramework.Res"
    "ponse\"\000\022\\\n\027GetImpedanceControlGain\022\031.Nrm"
    "k.IndyFramework.Empty\032$.Nrmk.IndyFramewo"
    "rk.ImpedanceGainSet\"\000\022W\n\023SetForceControl"
    "Gain\022 .Nrmk.IndyFramework.ForceGainSet\032\034"
    ".Nrmk.IndyFramework.Response\"\000\022T\n\023GetFor"
    "ceControlGain\022\031.Nrmk.IndyFramework.Empty"
    "\032 .Nrmk.IndyFramework.ForceGainSet\"\000\022U\n\022"
    "SetTestControlGain\022\037.Nrmk.IndyFramework."
    "TestGainSet\032\034.Nrmk.IndyFramework.Respons"
    "e\"\000\022R\n\022GetTestControlGain\022\031.Nrmk.IndyFra"
    "mework.Empty\032\037.Nrmk.IndyFramework.TestGa"
    "inSet\"\000\022Y\n\024SetCustomControlGain\022!.Nrmk.I"
    "ndyFramework.CustomGainSet\032\034.Nrmk.IndyFr"
    "amework.Response\"\000\022V\n\024GetCustomControlGa"
    "in\022\031.Nrmk.IndyFramework.Empty\032!.Nrmk.Ind"
    "yFramework.CustomGainSet\"\000\022V\n\031RestorFact"
    "oryControlGains\022\031.Nrmk.IndyFramework.Emp"
    "ty\032\034.Nrmk.IndyFramework.Response\"\000\022g\n\031Se"
    "tNewControllerTestOnOff\022*.Nrmk.IndyFrame"
    "work.NewControllerTestState\032\034.Nrmk.IndyF"
    "ramework.Response\"\000\022i\n\036GetNewControllerT"
    "estOnOffState\022\031.Nrmk.IndyFramework.Empty"
    "\032*.Nrmk.IndyFramework.NewControllerTestS"
    "tate\"\000\022f\n\035SetComplianceControlJointGain\022"
    "%.Nrmk.IndyFramework.ComplianceGainSet\032\034"
    ".Nrmk.IndyFramework.Response\"\000\022c\n\035GetCom"
    "plianceControlJointGain\022\031.Nrmk.IndyFrame"
    "work.Empty\032%.Nrmk.IndyFramework.Complian"
    "ceGainSet\"\000\022V\n\017SetFrictionComp\022#.Nrmk.In"
    "dyFramework.FrictionCompSet\032\034.Nrmk.IndyF"
    "ramework.Response\"\000\022S\n\017GetFrictionComp\022\031"
    ".Nrmk.IndyFramework.Empty\032#.Nrmk.IndyFra"
    "mework.FrictionCompSet\"\000\022Q\n\013SetMountPos\022"
    "\".Nrmk.IndyFramework.MountingAngles\032\034.Nr"
    "mk.IndyFramework.Response\"\000\022N\n\013GetMountP"
    "os\022\031.Nrmk.IndyFramework.Empty\032\".Nrmk.Ind"
    "yFramework.MountingAngles\"\000\022R\n\017GetIMUAut"
    "oMount\022\031.Nrmk.IndyFramework.Empty\032\".Nrmk"
    ".IndyFramework.MountingAngles\"\000\022U\n\017SetTo"
    "olProperty\022\".Nrmk.IndyFramework.ToolProp"
    "erties\032\034.Nrmk.IndyFramework.Response\"\000\022R"
    "\n\017GetToolProperty\022\031.Nrmk.IndyFramework.E"
    "mpty\032\".Nrmk.IndyFramework.ToolProperties"
    "\"\000\022R\n\021GetToolPropertyAt\022\027.Nrmk.IndyFrame"
    "work.Int\032\".Nrmk.IndyFramework.ToolProper"
    "ties\"\000\022^\n\023SetToolPropertyList\022\'.Nrmk.Ind"
    "yFramework.ToolPropertyEntries\032\034.Nrmk.In"
    "dyFramework.Response\"\000\022[\n\023GetToolPropert"
    "yList\022\031.Nrmk.IndyFramework.Empty\032\'.Nrmk."
    "IndyFramework.ToolPropertyEntries\"\000\022R\n\020G"
    "etToolFrameList\022\031.Nrmk.IndyFramework.Emp"
    "ty\032!.Nrmk.IndyFramework.ToolFrameList\"\000\022"
    "U\n\020SetToolFrameList\022!.Nrmk.IndyFramework"
    ".ToolFrameList\032\034.Nrmk.IndyFramework.Resp"
    "onse\"\000\022P\n\017GetRefFrameList\022\031.Nrmk.IndyFra"
    "mework.Empty\032 .Nrmk.IndyFramework.RefFra"
    "meList\"\000\022S\n\017SetRefFrameList\022 .Nrmk.IndyF"
    "ramework.RefFrameList\032\034.Nrmk.IndyFramewo"
    "rk.Response\"\000\022R\n\020GetCustomPosList\022\031.Nrmk"
    ".IndyFramework.Empty\032!.Nrmk.IndyFramewor"
    "k.CustomPosList\"\000\022U\n\020SetCustomPosList\022!."
    "Nrmk.IndyFramework.CustomPosList\032\034.Nrmk."
    "IndyFramework.Response\"\000\022Z\n\020SetCollSensL"
    "evel\022&.Nrmk.IndyFramework.CollisionSensL"
    "evel\032\034.Nrmk.IndyFramework.Response\"\000\022W\n\020"
    "GetCollSensLevel\022\031.Nrmk.IndyFramework.Em"
    "pty\032&.Nrmk.IndyFramework.CollisionSensLe"
    "vel\"\000\022[\n\020SetCollSensParam\022\'.Nrmk.IndyFra"
    "mework.CollisionThresholds\032\034.Nrmk.IndyFr"
    "amework.Response\"\000\022X\n\020GetCollSensParam\022\031"
    ".Nrmk.IndyFramework.Empty\032\'.Nrmk.IndyFra"
    "mework.CollisionThresholds\"\000\022_\n\027GetDefau"
    "ltCollSensParam\022\031.Nrmk.IndyFramework.Emp"
    "ty\032\'.Nrmk.IndyFramework.CollisionThresho"
    "lds\"\000\022T\n\rSetCollPolicy\022#.Nrmk.IndyFramew"
    "ork.CollisionPolicy\032\034.Nrmk.IndyFramework"
    ".Response\"\000\022Q\n\rGetCollPolicy\022\031.Nrmk.Indy"
    "Framework.Empty\032#.Nrmk.IndyFramework.Col"
    "lisionPolicy\"\000\022c\n\027SetOnStartProgramConfi"
    "g\022(.Nrmk.IndyFramework.OnStartProgramCon"
    "fig\032\034.Nrmk.IndyFramework.Response\"\000\022`\n\027G"
    "etOnStartProgramConfig\022\031.Nrmk.IndyFramew"
    "ork.Empty\032(.Nrmk.IndyFramework.OnStartPr"
    "ogramConfig\"\000\022S\n\026SetSimpleCollThreshold\022"
    "\031.Nrmk.IndyFramework.Empty\032\034.Nrmk.IndyFr"
    "amework.Response\"\000\022S\n\017SetSafetyLimits\022 ."
    "Nrmk.IndyFramework.SafetyLimits\032\034.Nrmk.I"
    "ndyFramework.Response\"\000\022P\n\017GetSafetyLimi"
    "ts\022\031.Nrmk.IndyFramework.Empty\032 .Nrmk.Ind"
    "yFramework.SafetyLimits\"\000\022X\n\023GetJointLim"
    "itConfig\022\031.Nrmk.IndyFramework.Empty\032$.Nr"
    "mk.IndyFramework.JointLimitConfig\"\000\022[\n\023S"
    "etJointLimitConfig\022$.Nrmk.IndyFramework."
    "JointLimitConfig\032\034.Nrmk.IndyFramework.Re"
    "sponse\"\000\022`\n\033GetOriginalJointLimitConfig\022"
    "\031.Nrmk.IndyFramework.Empty\032$.Nrmk.IndyFr"
    "amework.JointLimitConfig\"\000\022[\n\023SetSafetyS"
    "topConfig\022$.Nrmk.IndyFramework.SafetySto"
    "pConfig\032\034.Nrmk.IndyFramework.Response\"\000\022"
    "X\n\023GetSafetyStopConfig\022\031.Nrmk.IndyFramew"
    "ork.Empty\032$.Nrmk.IndyFramework.SafetySto"
    "pConfig\"\000\022i\n\022SaveSafetySnapshot\022).Nrmk.I"
    "ndyFramework.SaveSafetySnapshotReq\032&.Nrm"
    "k.IndyFramework.SafetySnapshotInfo\"\000\022Z\n\023"
    "ListSafetySnapshots\022\031.Nrmk.IndyFramework"
    ".Empty\032&.Nrmk.IndyFramework.SafetySnapsh"
    "otList\"\000\022]\n\025RestoreSafetySnapshot\022$.Nrmk"
    ".IndyFramework.SafetySnapshotId\032\034.Nrmk.I"
    "ndyFramework.Response\"\000\022\\\n\024DeleteSafetyS"
    "napshot\022$.Nrmk.IndyFramework.SafetySnaps"
    "hotId\032\034.Nrmk.IndyFramework.Response\"\000\022V\n"
    "\031RestorFactorySafetyConfig\022\031.Nrmk.IndyFr"
    "amework.Empty\032\034.Nrmk.IndyFramework.Respo"
    "nse\"\000\022V\n\017GetReducedRatio\022\031.Nrmk.IndyFram"
    "ework.Empty\032&.Nrmk.IndyFramework.GetRedu"
    "cedRatioRes\"\000\022V\n\017GetReducedSpeed\022\031.Nrmk."
    "IndyFramework.Empty\032&.Nrmk.IndyFramework"
    ".GetReducedSpeedRes\"\000\022Y\n\017SetReducedSpeed"
    "\022&.Nrmk.IndyFramework.SetReducedSpeedReq"
    "\032\034.Nrmk.IndyFramework.Response\"\000\022W\n\021SetF"
    "TSensorConfig\022\".Nrmk.IndyFramework.FTSen"
    "sorDevice\032\034.Nrmk.IndyFramework.Response\""
    "\000\022T\n\021GetFTSensorConfig\022\031.Nrmk.IndyFramew"
    "ork.Empty\032\".Nrmk.IndyFramework.FTSensorD"
    "evice\"\000\022U\n\024GetFTSensorConfigFor\022\027.Nrmk.I"
    "ndyFramework.Int\032\".Nrmk.IndyFramework.FT"
    "SensorDevice\"\000\022S\n\017SetTeleOpParams\022 .Nrmk"
    ".IndyFramework.TeleOpParams\032\034.Nrmk.IndyF"
    "ramework.Response\"\000\022P\n\017GetTeleOpParams\022\031"
    ".Nrmk.IndyFramework.Empty\032 .Nrmk.IndyFra"
    "mework.TeleOpParams\"\000\022X\n\023GetKinematicsPa"
    "rams\022\031.Nrmk.IndyFramework.Empty\032$.Nrmk.I"
    "ndyFramework.KinematicsParams\"\000\022_\n\026GetCo"
    "llisonModelMargin\022\031.Nrmk.IndyFramework.E"
    "mpty\032(.Nrmk.IndyFramework.CollisionModel"
    "Margin\"\000\022b\n\026SetCollisonModelMargin\022(.Nrm"
    "k.IndyFramework.CollisionModelMargin\032\034.N"
    "rmk.IndyFramework.Response\"\000\022U\n\020SetToolS"
    "hapeList\022!.Nrmk.IndyFramework.ToolShapeL"
    "ist\032\034.Nrmk.IndyFramework.Response\"\000\022R\n\020G"
    "etToolShapeList\022\031.Nrmk.IndyFramework.Emp"
    "ty\032!.Nrmk.IndyFramework.ToolShapeList\"\000\022"
    "Y\n\022SetEnvironmentList\022#.Nrmk.IndyFramewo"
    "rk.EnvironmentList\032\034.Nrmk.IndyFramework."
    "Response\"\000\022V\n\022GetEnvironmentList\022\031.Nrmk."
    "IndyFramework.Empty\032#.Nrmk.IndyFramework"
    ".EnvironmentList\"\000\022[\n\023SetSensorlessParam"
    "s\022$.Nrmk.IndyFramework.SensorlessParams\032"
    "\034.Nrmk.IndyFramework.Response\"\000\022X\n\023GetSe"
    "nsorlessParams\022\031.Nrmk.IndyFramework.Empt"
    "y\032$.Nrmk.IndyFramework.SensorlessParams\""
    "\000\022]\n\027GetWeldingMachineConfig\022\031.Nrmk.Indy"
    "Framework.Empty\032%.Nrmk.IndyFramework.Wel"
    "dingConfigInfo\"\000\022`\n\027SetWeldingMachineCon"
    "fig\022%.Nrmk.IndyFramework.WeldingConfigIn"
    "fo\032\034.Nrmk.IndyFramework.Response\"\000\022X\n\023Ge"
    "tWeldPositionList\022\031.Nrmk.IndyFramework.E"
    "mpty\032$.Nrmk.IndyFramework.WeldPositionLi"
    "st\"\000\022[\n\023SetWeldPositionList\022$.Nrmk.IndyF"
    "ramework.WeldPositionList\032\034.Nrmk.IndyFra"
    "mework.Response\"\000\022a\n\026SetOperationModeCon"
    "fig\022\'.Nrmk.IndyFramework.OperationModeCo"
    "nfig\032\034.Nrmk.IndyFramework.Response\"\000\022^\n\026"
    "GetOperationModeConfig\022\031.Nrmk.IndyFramew"
    "ork.Empty\032\'.Nrmk.IndyFramework.Operation"
    "ModeConfig\"\000b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_config_2eproto_deps[2] =
    {
        &::descriptor_table_common_5fmsgs_2eproto,
        &::descriptor_table_config_5fmsgs_2eproto,
};
static ::absl::once_flag descriptor_table_config_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_config_2eproto = {
    false,
    false,
    9700,
    descriptor_table_protodef_config_2eproto,
    "config.proto",
    &descriptor_table_config_2eproto_once,
    descriptor_table_config_2eproto_deps,
    2,
    0,
    schemas,
    file_default_instances,
    TableStruct_config_2eproto::offsets,
    nullptr,
    file_level_enum_descriptors_config_2eproto,
    file_level_service_descriptors_config_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_config_2eproto_getter() {
  return &descriptor_table_config_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_config_2eproto(&descriptor_table_config_2eproto);
namespace Nrmk {
namespace IndyFramework {
// @@protoc_insertion_point(namespace_scope)
}  // namespace IndyFramework
}  // namespace Nrmk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
