// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device.proto

#include "device.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Nrmk {
namespace IndyFramework {
}  // namespace IndyFramework
}  // namespace Nrmk
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_device_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_device_2eproto = nullptr;
const ::uint32_t TableStruct_device_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_device_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\014device.proto\022\022Nrmk.IndyFramework\032\021devi"
    "ce_msgs.proto\032\021common_msgs.proto2\333/\n\006Dev"
    "ice\022J\n\tSetBrakes\022\035.Nrmk.IndyFramework.Mo"
    "torList\032\034.Nrmk.IndyFramework.Response\"\000\022"
    "H\n\013SetServoAll\022\031.Nrmk.IndyFramework.Stat"
    "e\032\034.Nrmk.IndyFramework.Response\"\000\022E\n\010Set"
    "Servo\022\031.Nrmk.IndyFramework.Servo\032\034.Nrmk."
    "IndyFramework.Response\"\000\022L\n\013SimDIConfig\022"
    "\035.Nrmk.IndyFramework.DISignals\032\034.Nrmk.In"
    "dyFramework.Response\"\000\022H\n\005SetDI\022\037.Nrmk.I"
    "ndyFramework.DigitalList\032\034.Nrmk.IndyFram"
    "ework.Response\"\000\022H\n\005SetDO\022\037.Nrmk.IndyFra"
    "mework.DigitalList\032\034.Nrmk.IndyFramework."
    "Response\"\000\022Q\n\010SetEndDI\022%.Nrmk.IndyFramew"
    "ork.EndtoolSignalList\032\034.Nrmk.IndyFramewo"
    "rk.Response\"\000\022Q\n\010SetEndDO\022%.Nrmk.IndyFra"
    "mework.EndtoolSignalList\032\034.Nrmk.IndyFram"
    "ework.Response\"\000\022G\n\005SetAI\022\036.Nrmk.IndyFra"
    "mework.AnalogList\032\034.Nrmk.IndyFramework.R"
    "esponse\"\000\022G\n\005SetAO\022\036.Nrmk.IndyFramework."
    "AnalogList\032\034.Nrmk.IndyFramework.Response"
    "\"\000\022J\n\010SetEndAI\022\036.Nrmk.IndyFramework.Anal"
    "ogList\032\034.Nrmk.IndyFramework.Response\"\000\022J"
    "\n\010SetEndAO\022\036.Nrmk.IndyFramework.AnalogLi"
    "st\032\034.Nrmk.IndyFramework.Response\"\000\022D\n\013Ex"
    "ecuteTool\022\030.Nrmk.IndyFramework.Name\032\031.Nr"
    "mk.IndyFramework.Empty\"\000\022S\n\rSetEndRS485R"
    "x\022\".Nrmk.IndyFramework.EndtoolRS485Rx\032\034."
    "Nrmk.IndyFramework.Response\"\000\022P\n\rGetEndR"
    "S485Rx\022\031.Nrmk.IndyFramework.Empty\032\".Nrmk"
    ".IndyFramework.EndtoolRS485Rx\"\000\022Q\n\020GetEn"
    "dRS485RxFor\022\027.Nrmk.IndyFramework.Int\032\".N"
    "rmk.IndyFramework.EndtoolRS485Rx\"\000\022P\n\rGe"
    "tEndRS485Tx\022\031.Nrmk.IndyFramework.Empty\032\""
    ".Nrmk.IndyFramework.EndtoolRS485Tx\"\000\022Q\n\020"
    "GetEndRS485TxFor\022\027.Nrmk.IndyFramework.In"
    "t\032\".Nrmk.IndyFramework.EndtoolRS485Tx\"\000\022"
    "J\n\014SetEndLedDim\022\035.Nrmk.IndyFramework.End"
    "LedDim\032\031.Nrmk.IndyFramework.Empty\"\000\022E\n\005G"
    "etDI\022\031.Nrmk.IndyFramework.Empty\032\037.Nrmk.I"
    "ndyFramework.DigitalList\"\000\022E\n\005GetDO\022\031.Nr"
    "mk.IndyFramework.Empty\032\037.Nrmk.IndyFramew"
    "ork.DigitalList\"\000\022N\n\010GetEndDI\022\031.Nrmk.Ind"
    "yFramework.Empty\032%.Nrmk.IndyFramework.En"
    "dtoolSignalList\"\000\022N\n\010GetEndDO\022\031.Nrmk.Ind"
    "yFramework.Empty\032%.Nrmk.IndyFramework.En"
    "dtoolSignalList\"\000\022D\n\005GetAI\022\031.Nrmk.IndyFr"
    "amework.Empty\032\036.Nrmk.IndyFramework.Analo"
    "gList\"\000\022D\n\005GetAO\022\031.Nrmk.IndyFramework.Em"
    "pty\032\036.Nrmk.IndyFramework.AnalogList\"\000\022G\n"
    "\010GetEndAI\022\031.Nrmk.IndyFramework.Empty\032\036.N"
    "rmk.IndyFramework.AnalogList\"\000\022G\n\010GetEnd"
    "AO\022\031.Nrmk.IndyFramework.Empty\032\036.Nrmk.Ind"
    "yFramework.AnalogList\"\000\022L\n\rGetDeviceInfo"
    "\022\031.Nrmk.IndyFramework.Empty\032\036.Nrmk.IndyF"
    "ramework.DeviceInfo\"\000\022Z\n\024GetBrakeControl"
    "Style\022\031.Nrmk.IndyFramework.Empty\032%.Nrmk."
    "IndyFramework.BrakeControlStyle\"\000\022U\n\020Set"
    "SanderCommand\022!.Nrmk.IndyFramework.Sande"
    "rCommand\032\034.Nrmk.IndyFramework.Response\"\000"
    "\022R\n\020GetSanderCommand\022\031.Nrmk.IndyFramewor"
    "k.Empty\032!.Nrmk.IndyFramework.SanderComma"
    "nd\"\000\022S\n\023GetSanderCommandFor\022\027.Nrmk.IndyF"
    "ramework.Int\032!.Nrmk.IndyFramework.Sander"
    "Command\"\000\022P\n\017GetFTSensorData\022\031.Nrmk.Indy"
    "Framework.Empty\032 .Nrmk.IndyFramework.FTS"
    "ensorData\"\000\022Q\n\022GetFTSensorDataFor\022\027.Nrmk"
    ".IndyFramework.Int\032 .Nrmk.IndyFramework."
    "FTSensorData\"\000\022H\n\013GetConveyor\022\031.Nrmk.Ind"
    "yFramework.Empty\032\034.Nrmk.IndyFramework.Co"
    "nveyor\"\000\022K\n\017SetConveyorName\022\030.Nrmk.IndyF"
    "ramework.Name\032\034.Nrmk.IndyFramework.Respo"
    "nse\"\000\022M\n\021SetConveyorByName\022\030.Nrmk.IndyFr"
    "amework.Name\032\034.Nrmk.IndyFramework.Respon"
    "se\"\000\022Q\n\022SetConveyorEncoder\022\033.Nrmk.IndyFr"
    "amework.Encoder\032\034.Nrmk.IndyFramework.Res"
    "ponse\"\000\022Q\n\022SetConveyorTrigger\022\033.Nrmk.Ind"
    "yFramework.Trigger\032\034.Nrmk.IndyFramework."
    "Response\"\000\022N\n\021SetConveyorOffset\022\031.Nrmk.I"
    "ndyFramework.Float\032\034.Nrmk.IndyFramework."
    "Response\"\000\022Q\n\026SetConveyorLockedJoint\022\027.N"
    "rmk.IndyFramework.Int\032\034.Nrmk.IndyFramewo"
    "rk.Response\"\000\022N\n\023SetConveyorToolLink\022\027.N"
    "rmk.IndyFramework.Int\032\034.Nrmk.IndyFramewo"
    "rk.Response\"\000\022N\n\023SetConveyorArmIndex\022\027.N"
    "rmk.IndyFramework.Int\032\034.Nrmk.IndyFramewo"
    "rk.Response\"\000\022W\n\027SetConveyorStartingPose"
    "\022\034.Nrmk.IndyFramework.PosePair\032\034.Nrmk.In"
    "dyFramework.Response\"\000\022W\n\027SetConveyorTer"
    "minalPose\022\034.Nrmk.IndyFramework.PosePair\032"
    "\034.Nrmk.IndyFramework.Response\"\000\022R\n\020GetCo"
    "nveyorState\022\031.Nrmk.IndyFramework.Empty\032!"
    ".Nrmk.IndyFramework.ConveyorState\"\000\022f\n\032G"
    "etConveyorObjectDistances\022\031.Nrmk.IndyFra"
    "mework.Empty\032+.Nrmk.IndyFramework.Convey"
    "orObjectDistances\"\000\022T\n\016GetLoadFactors\022\031."
    "Nrmk.IndyFramework.Empty\032%.Nrmk.IndyFram"
    "ework.GetLoadFactorsRes\"\000\022W\n\013SetAutoMode"
    "\022\".Nrmk.IndyFramework.SetAutoModeReq\032\".N"
    "rmk.IndyFramework.SetAutoModeRes\"\000\022R\n\rCh"
    "eckAutoMode\022\031.Nrmk.IndyFramework.Empty\032$"
    ".Nrmk.IndyFramework.CheckAutoModeRes\"\000\022X"
    "\n\020CheckReducedMode\022\031.Nrmk.IndyFramework."
    "Empty\032\'.Nrmk.IndyFramework.CheckReducedM"
    "odeRes\"\000\022^\n\026GetSafetyFunctionState\022\031.Nrm"
    "k.IndyFramework.Empty\032\'.Nrmk.IndyFramewo"
    "rk.SafetyFunctionState\"\000\022`\n\025RequestSafet"
    "yFunction\022\'.Nrmk.IndyFramework.SafetyFun"
    "ctionState\032\034.Nrmk.IndyFramework.Response"
    "\"\000\022Z\n\024GetSafetyControlData\022\031.Nrmk.IndyFr"
    "amework.Empty\032%.Nrmk.IndyFramework.Safet"
    "yControlData\"\000\022W\n\017CommitViolation\022$.Nrmk"
    ".IndyFramework.ViolationRequest\032\034.Nrmk.I"
    "ndyFramework.Response\"\000\022N\n\016GetGripperDat"
    "a\022\031.Nrmk.IndyFramework.Empty\032\037.Nrmk.Indy"
    "Framework.GripperData\"\000\022O\n\021GetGripperDat"
    "aFor\022\027.Nrmk.IndyFramework.Int\032\037.Nrmk.Ind"
    "yFramework.GripperData\"\000\022T\n\021SetGripperCo"
    "mmand\022\".Nrmk.IndyFramework.GripperComman"
    "d\032\031.Nrmk.IndyFramework.Empty\"\000\022e\n\025AddPho"
    "toneoCalibPoint\022,.Nrmk.IndyFramework.Add"
    "PhotoneoCalibPointReq\032\034.Nrmk.IndyFramewo"
    "rk.Response\"\000\022]\n\024GetPhotoneoDetection\022!."
    "Nrmk.IndyFramework.VisionRequest\032 .Nrmk."
    "IndyFramework.VisionResult\"\000\022]\n\024GetPhoto"
    "neoRetrieval\022!.Nrmk.IndyFramework.Vision"
    "Request\032 .Nrmk.IndyFramework.VisionResul"
    "t\"\000\022]\n\021ConfigurePickit3D\022(.Nrmk.IndyFram"
    "ework.ConfigurePickit3DReq\032\034.Nrmk.IndyFr"
    "amework.Response\"\000\022]\n\024GetPickit3DDetecti"
    "on\022!.Nrmk.IndyFramework.VisionRequest\032 ."
    "Nrmk.IndyFramework.VisionResult\"\000\022]\n\024Get"
    "Pickit3DRetrieval\022!.Nrmk.IndyFramework.V"
    "isionRequest\032 .Nrmk.IndyFramework.Vision"
    "Result\"\000\022L\n\016GetRTTaskTimes\022\031.Nrmk.IndyFr"
    "amework.Empty\032\035.Nrmk.IndyFramework.TaskT"
    "imes\"\000\022]\n\022SocketCmdSetConfig\022\'.Nrmk.Indy"
    "Framework.SocketCommandConfig\032\034.Nrmk.Ind"
    "yFramework.Response\"\000\022Z\n\022SocketCmdGetCon"
    "fig\022\031.Nrmk.IndyFramework.Empty\032\'.Nrmk.In"
    "dyFramework.SocketCommandConfig\"\000\022V\n\016Soc"
    "ketCmdStart\022\031.Nrmk.IndyFramework.Empty\032\'"
    ".Nrmk.IndyFramework.SocketCommandStatus\""
    "\000\022U\n\rSocketCmdStop\022\031.Nrmk.IndyFramework."
    "Empty\032\'.Nrmk.IndyFramework.SocketCommand"
    "Status\"\000\022a\n\021SocketCmdSendData\022!.Nrmk.Ind"
    "yFramework.SocketPayload\032\'.Nrmk.IndyFram"
    "ework.SocketCommandStatus\"\000\022X\n\026SocketCmd"
    "GetLatestData\022\031.Nrmk.IndyFramework.Empty"
    "\032!.Nrmk.IndyFramework.SocketPayload\"\000\022_\n"
    "\025SetInspireHandCommand\022&.Nrmk.IndyFramew"
    "ork.InspireHandCommand\032\034.Nrmk.IndyFramew"
    "ork.Response\"\000\022V\n\023GetInspireHandState\022\027."
    "Nrmk.IndyFramework.Int\032$.Nrmk.IndyFramew"
    "ork.InspireHandState\"\000b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_device_2eproto_deps[2] =
    {
        &::descriptor_table_common_5fmsgs_2eproto,
        &::descriptor_table_device_5fmsgs_2eproto,
};
static ::absl::once_flag descriptor_table_device_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_device_2eproto = {
    false,
    false,
    6190,
    descriptor_table_protodef_device_2eproto,
    "device.proto",
    &descriptor_table_device_2eproto_once,
    descriptor_table_device_2eproto_deps,
    2,
    0,
    schemas,
    file_default_instances,
    TableStruct_device_2eproto::offsets,
    nullptr,
    file_level_enum_descriptors_device_2eproto,
    file_level_service_descriptors_device_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_device_2eproto_getter() {
  return &descriptor_table_device_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_device_2eproto(&descriptor_table_device_2eproto);
namespace Nrmk {
namespace IndyFramework {
// @@protoc_insertion_point(namespace_scope)
}  // namespace IndyFramework
}  // namespace Nrmk
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
