// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mimic.proto

#include "mimic.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace IndyFramework {
namespace Protobuf {
namespace MimicServer {
}  // namespace MimicServer
}  // namespace Protobuf
}  // namespace IndyFramework
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_mimic_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_mimic_2eproto = nullptr;
const ::uint32_t TableStruct_mimic_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_mimic_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\013mimic.proto\022\"IndyFramework.Protobuf.Mi"
    "micServer\032\020mimic_msgs.proto2\277\004\n\tMoveMimi"
    "c\022n\n\017SetRobotAddress\022+.IndyFramework.Pro"
    "tobuf.MimicServer.Address\032,.IndyFramewor"
    "k.Protobuf.MimicServer.Response\"\000\022o\n\014Get"
    "SkillList\022).IndyFramework.Protobuf.Mimic"
    "Server.Empty\0322.IndyFramework.Protobuf.Mi"
    "micServer.MimicSkillList\"\000\022y\n\014GetSkillHo"
    "me\0222.IndyFramework.Protobuf.MimicServer."
    "MimicSkillName\0323.IndyFramework.Protobuf."
    "MimicServer.GetSkillHomeRes\"\000\022n\n\010RunSkil"
    "l\0222.IndyFramework.Protobuf.MimicServer.M"
    "imicSkillName\032,.IndyFramework.Protobuf.M"
    "imicServer.Response\"\000\022f\n\tStopSkill\022).Ind"
    "yFramework.Protobuf.MimicServer.Empty\032,."
    "IndyFramework.Protobuf.MimicServer.Respo"
    "nse\"\000b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_mimic_2eproto_deps[1] =
    {
        &::descriptor_table_mimic_5fmsgs_2eproto,
};
static ::absl::once_flag descriptor_table_mimic_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_mimic_2eproto = {
    false,
    false,
    653,
    descriptor_table_protodef_mimic_2eproto,
    "mimic.proto",
    &descriptor_table_mimic_2eproto_once,
    descriptor_table_mimic_2eproto_deps,
    1,
    0,
    schemas,
    file_default_instances,
    TableStruct_mimic_2eproto::offsets,
    nullptr,
    file_level_enum_descriptors_mimic_2eproto,
    file_level_service_descriptors_mimic_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_mimic_2eproto_getter() {
  return &descriptor_table_mimic_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_mimic_2eproto(&descriptor_table_mimic_2eproto);
namespace IndyFramework {
namespace Protobuf {
namespace MimicServer {
// @@protoc_insertion_point(namespace_scope)
}  // namespace MimicServer
}  // namespace Protobuf
}  // namespace IndyFramework
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
