// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shared_msgs.proto

#include "shared_msgs.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace IndyFramework {
namespace Protobuf {
namespace Shared {
        template <typename>
PROTOBUF_CONSTEXPR NamedReferencePosition::NamedReferencePosition(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_.tpos_)*/ {},
      /*decltype(_impl_.tpos0_)*/ {},
      /*decltype(_impl_.tpos1_)*/ {},
      /*decltype(_impl_.tpos2_)*/ {},
      /*decltype(_impl_.jpos0_)*/ {},
      /*decltype(_impl_.jpos1_)*/ {},
      /*decltype(_impl_.jpos2_)*/ {},
      /*decltype(_impl_.name_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_._cached_size_)*/ {},
    } {}
struct NamedReferencePositionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NamedReferencePositionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NamedReferencePositionDefaultTypeInternal() {}
  union {
    NamedReferencePosition _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NamedReferencePositionDefaultTypeInternal _NamedReferencePosition_default_instance_;
}  // namespace Shared
}  // namespace Protobuf
}  // namespace IndyFramework
static ::_pb::Metadata file_level_metadata_shared_5fmsgs_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_shared_5fmsgs_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_shared_5fmsgs_2eproto = nullptr;
const ::uint32_t TableStruct_shared_5fmsgs_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::IndyFramework::Protobuf::Shared::NamedReferencePosition, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::IndyFramework::Protobuf::Shared::NamedReferencePosition, _impl_.name_),
    PROTOBUF_FIELD_OFFSET(::IndyFramework::Protobuf::Shared::NamedReferencePosition, _impl_.tpos_),
    PROTOBUF_FIELD_OFFSET(::IndyFramework::Protobuf::Shared::NamedReferencePosition, _impl_.tpos0_),
    PROTOBUF_FIELD_OFFSET(::IndyFramework::Protobuf::Shared::NamedReferencePosition, _impl_.tpos1_),
    PROTOBUF_FIELD_OFFSET(::IndyFramework::Protobuf::Shared::NamedReferencePosition, _impl_.tpos2_),
    PROTOBUF_FIELD_OFFSET(::IndyFramework::Protobuf::Shared::NamedReferencePosition, _impl_.jpos0_),
    PROTOBUF_FIELD_OFFSET(::IndyFramework::Protobuf::Shared::NamedReferencePosition, _impl_.jpos1_),
    PROTOBUF_FIELD_OFFSET(::IndyFramework::Protobuf::Shared::NamedReferencePosition, _impl_.jpos2_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::IndyFramework::Protobuf::Shared::NamedReferencePosition)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::IndyFramework::Protobuf::Shared::_NamedReferencePosition_default_instance_._instance,
};
const char descriptor_table_protodef_shared_5fmsgs_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\021shared_msgs.proto\022\035IndyFramework.Proto"
    "buf.Shared\"\216\001\n\026NamedReferencePosition\022\014\n"
    "\004name\030\001 \001(\t\022\014\n\004tpos\030\002 \003(\002\022\r\n\005tpos0\030\003 \003(\002"
    "\022\r\n\005tpos1\030\004 \003(\002\022\r\n\005tpos2\030\005 \003(\002\022\r\n\005jpos0\030"
    "\006 \003(\002\022\r\n\005jpos1\030\007 \003(\002\022\r\n\005jpos2\030\010 \003(\002b\006pro"
    "to3"
};
static ::absl::once_flag descriptor_table_shared_5fmsgs_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_shared_5fmsgs_2eproto = {
    false,
    false,
    203,
    descriptor_table_protodef_shared_5fmsgs_2eproto,
    "shared_msgs.proto",
    &descriptor_table_shared_5fmsgs_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_shared_5fmsgs_2eproto::offsets,
    file_level_metadata_shared_5fmsgs_2eproto,
    file_level_enum_descriptors_shared_5fmsgs_2eproto,
    file_level_service_descriptors_shared_5fmsgs_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_shared_5fmsgs_2eproto_getter() {
  return &descriptor_table_shared_5fmsgs_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_shared_5fmsgs_2eproto(&descriptor_table_shared_5fmsgs_2eproto);
namespace IndyFramework {
namespace Protobuf {
namespace Shared {
// ===================================================================

class NamedReferencePosition::_Internal {
 public:
};

NamedReferencePosition::NamedReferencePosition(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:IndyFramework.Protobuf.Shared.NamedReferencePosition)
}
NamedReferencePosition::NamedReferencePosition(const NamedReferencePosition& from) : ::google::protobuf::Message() {
  NamedReferencePosition* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.tpos_){from._impl_.tpos_},
      decltype(_impl_.tpos0_){from._impl_.tpos0_},
      decltype(_impl_.tpos1_){from._impl_.tpos1_},
      decltype(_impl_.tpos2_){from._impl_.tpos2_},
      decltype(_impl_.jpos0_){from._impl_.jpos0_},
      decltype(_impl_.jpos1_){from._impl_.jpos1_},
      decltype(_impl_.jpos2_){from._impl_.jpos2_},
      decltype(_impl_.name_){},
      /*decltype(_impl_._cached_size_)*/ {},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.name_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), _this->GetArenaForAllocation());
  }

  // @@protoc_insertion_point(copy_constructor:IndyFramework.Protobuf.Shared.NamedReferencePosition)
}
inline void NamedReferencePosition::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.tpos_){arena},
      decltype(_impl_.tpos0_){arena},
      decltype(_impl_.tpos1_){arena},
      decltype(_impl_.tpos2_){arena},
      decltype(_impl_.jpos0_){arena},
      decltype(_impl_.jpos1_){arena},
      decltype(_impl_.jpos2_){arena},
      decltype(_impl_.name_){},
      /*decltype(_impl_._cached_size_)*/ {},
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.name_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}
NamedReferencePosition::~NamedReferencePosition() {
  // @@protoc_insertion_point(destructor:IndyFramework.Protobuf.Shared.NamedReferencePosition)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void NamedReferencePosition::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.tpos_.~RepeatedField();
  _impl_.tpos0_.~RepeatedField();
  _impl_.tpos1_.~RepeatedField();
  _impl_.tpos2_.~RepeatedField();
  _impl_.jpos0_.~RepeatedField();
  _impl_.jpos1_.~RepeatedField();
  _impl_.jpos2_.~RepeatedField();
  _impl_.name_.Destroy();
}
void NamedReferencePosition::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void NamedReferencePosition::Clear() {
// @@protoc_insertion_point(message_clear_start:IndyFramework.Protobuf.Shared.NamedReferencePosition)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_tpos()->Clear();
  _internal_mutable_tpos0()->Clear();
  _internal_mutable_tpos1()->Clear();
  _internal_mutable_tpos2()->Clear();
  _internal_mutable_jpos0()->Clear();
  _internal_mutable_jpos1()->Clear();
  _internal_mutable_jpos2()->Clear();
  _impl_.name_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* NamedReferencePosition::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 8, 0, 73, 2> NamedReferencePosition::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    8, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967040,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_NamedReferencePosition_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated float jpos2 = 8;
    {::_pbi::TcParser::FastF32P1,
     {66, 63, 0, PROTOBUF_FIELD_OFFSET(NamedReferencePosition, _impl_.jpos2_)}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(NamedReferencePosition, _impl_.name_)}},
    // repeated float tpos = 2;
    {::_pbi::TcParser::FastF32P1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(NamedReferencePosition, _impl_.tpos_)}},
    // repeated float tpos0 = 3;
    {::_pbi::TcParser::FastF32P1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(NamedReferencePosition, _impl_.tpos0_)}},
    // repeated float tpos1 = 4;
    {::_pbi::TcParser::FastF32P1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(NamedReferencePosition, _impl_.tpos1_)}},
    // repeated float tpos2 = 5;
    {::_pbi::TcParser::FastF32P1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(NamedReferencePosition, _impl_.tpos2_)}},
    // repeated float jpos0 = 6;
    {::_pbi::TcParser::FastF32P1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(NamedReferencePosition, _impl_.jpos0_)}},
    // repeated float jpos1 = 7;
    {::_pbi::TcParser::FastF32P1,
     {58, 63, 0, PROTOBUF_FIELD_OFFSET(NamedReferencePosition, _impl_.jpos1_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(NamedReferencePosition, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated float tpos = 2;
    {PROTOBUF_FIELD_OFFSET(NamedReferencePosition, _impl_.tpos_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float tpos0 = 3;
    {PROTOBUF_FIELD_OFFSET(NamedReferencePosition, _impl_.tpos0_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float tpos1 = 4;
    {PROTOBUF_FIELD_OFFSET(NamedReferencePosition, _impl_.tpos1_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float tpos2 = 5;
    {PROTOBUF_FIELD_OFFSET(NamedReferencePosition, _impl_.tpos2_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float jpos0 = 6;
    {PROTOBUF_FIELD_OFFSET(NamedReferencePosition, _impl_.jpos0_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float jpos1 = 7;
    {PROTOBUF_FIELD_OFFSET(NamedReferencePosition, _impl_.jpos1_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float jpos2 = 8;
    {PROTOBUF_FIELD_OFFSET(NamedReferencePosition, _impl_.jpos2_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
  }},
  // no aux_entries
  {{
    "\64\4\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
    "IndyFramework.Protobuf.Shared.NamedReferencePosition"
    "name"
  }},
};

::uint8_t* NamedReferencePosition::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:IndyFramework.Protobuf.Shared.NamedReferencePosition)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "IndyFramework.Protobuf.Shared.NamedReferencePosition.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // repeated float tpos = 2;
  if (this->_internal_tpos_size() > 0) {
    target = stream->WriteFixedPacked(2, _internal_tpos(), target);
  }

  // repeated float tpos0 = 3;
  if (this->_internal_tpos0_size() > 0) {
    target = stream->WriteFixedPacked(3, _internal_tpos0(), target);
  }

  // repeated float tpos1 = 4;
  if (this->_internal_tpos1_size() > 0) {
    target = stream->WriteFixedPacked(4, _internal_tpos1(), target);
  }

  // repeated float tpos2 = 5;
  if (this->_internal_tpos2_size() > 0) {
    target = stream->WriteFixedPacked(5, _internal_tpos2(), target);
  }

  // repeated float jpos0 = 6;
  if (this->_internal_jpos0_size() > 0) {
    target = stream->WriteFixedPacked(6, _internal_jpos0(), target);
  }

  // repeated float jpos1 = 7;
  if (this->_internal_jpos1_size() > 0) {
    target = stream->WriteFixedPacked(7, _internal_jpos1(), target);
  }

  // repeated float jpos2 = 8;
  if (this->_internal_jpos2_size() > 0) {
    target = stream->WriteFixedPacked(8, _internal_jpos2(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:IndyFramework.Protobuf.Shared.NamedReferencePosition)
  return target;
}

::size_t NamedReferencePosition::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:IndyFramework.Protobuf.Shared.NamedReferencePosition)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float tpos = 2;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_tpos_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated float tpos0 = 3;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_tpos0_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated float tpos1 = 4;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_tpos1_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated float tpos2 = 5;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_tpos2_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated float jpos0 = 6;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_jpos0_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated float jpos1 = 7;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_jpos1_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated float jpos2 = 8;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_jpos2_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData NamedReferencePosition::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    NamedReferencePosition::MergeImpl
};
const ::google::protobuf::Message::ClassData*NamedReferencePosition::GetClassData() const { return &_class_data_; }


void NamedReferencePosition::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<NamedReferencePosition*>(&to_msg);
  auto& from = static_cast<const NamedReferencePosition&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:IndyFramework.Protobuf.Shared.NamedReferencePosition)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_tpos()->MergeFrom(from._internal_tpos());
  _this->_internal_mutable_tpos0()->MergeFrom(from._internal_tpos0());
  _this->_internal_mutable_tpos1()->MergeFrom(from._internal_tpos1());
  _this->_internal_mutable_tpos2()->MergeFrom(from._internal_tpos2());
  _this->_internal_mutable_jpos0()->MergeFrom(from._internal_jpos0());
  _this->_internal_mutable_jpos1()->MergeFrom(from._internal_jpos1());
  _this->_internal_mutable_jpos2()->MergeFrom(from._internal_jpos2());
  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NamedReferencePosition::CopyFrom(const NamedReferencePosition& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:IndyFramework.Protobuf.Shared.NamedReferencePosition)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool NamedReferencePosition::IsInitialized() const {
  return true;
}

void NamedReferencePosition::InternalSwap(NamedReferencePosition* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.tpos_.InternalSwap(&other->_impl_.tpos_);
  _impl_.tpos0_.InternalSwap(&other->_impl_.tpos0_);
  _impl_.tpos1_.InternalSwap(&other->_impl_.tpos1_);
  _impl_.tpos2_.InternalSwap(&other->_impl_.tpos2_);
  _impl_.jpos0_.InternalSwap(&other->_impl_.jpos0_);
  _impl_.jpos1_.InternalSwap(&other->_impl_.jpos1_);
  _impl_.jpos2_.InternalSwap(&other->_impl_.jpos2_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, lhs_arena,
                                       &other->_impl_.name_, rhs_arena);
}

::google::protobuf::Metadata NamedReferencePosition::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_shared_5fmsgs_2eproto_getter, &descriptor_table_shared_5fmsgs_2eproto_once,
      file_level_metadata_shared_5fmsgs_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Shared
}  // namespace Protobuf
}  // namespace IndyFramework
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
