// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: teleop.proto

#include "teleop.pb.h"
#include "teleop.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace Nrmk {
namespace IndyFramework {

static const char* TeleOp_method_names[] = {
  "/Nrmk.IndyFramework.TeleOp/SetObstacleInfo",
  "/Nrmk.IndyFramework.TeleOp/GetObstacleInfo",
  "/Nrmk.IndyFramework.TeleOp/GetCollisionSpheres",
  "/Nrmk.IndyFramework.TeleOp/GetJointConstraintConfig",
  "/Nrmk.IndyFramework.TeleOp/GetSelfCollisionPairs",
  "/Nrmk.IndyFramework.TeleOp/GetPlaneConstraintConfig",
  "/Nrmk.IndyFramework.TeleOp/GetStaticObstacleConstraintConfig",
  "/Nrmk.IndyFramework.TeleOp/GetDynamicObstacleConstraintConfig",
  "/Nrmk.IndyFramework.TeleOp/GetOrientationDeviationConfig",
  "/Nrmk.IndyFramework.TeleOp/GetDesiredPosition",
  "/Nrmk.IndyFramework.TeleOp/GetCurrentPosition",
};

std::unique_ptr< TeleOp::Stub> TeleOp::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TeleOp::Stub> stub(new TeleOp::Stub(channel, options));
  return stub;
}

TeleOp::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SetObstacleInfo_(TeleOp_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetObstacleInfo_(TeleOp_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetCollisionSpheres_(TeleOp_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetJointConstraintConfig_(TeleOp_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetSelfCollisionPairs_(TeleOp_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetPlaneConstraintConfig_(TeleOp_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetStaticObstacleConstraintConfig_(TeleOp_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetDynamicObstacleConstraintConfig_(TeleOp_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetOrientationDeviationConfig_(TeleOp_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetDesiredPosition_(TeleOp_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetCurrentPosition_(TeleOp_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TeleOp::Stub::SetObstacleInfo(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::ObstacleInfo& request, ::Nrmk::IndyFramework::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Nrmk::IndyFramework::ObstacleInfo, ::Nrmk::IndyFramework::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetObstacleInfo_, context, request, response);
}

void TeleOp::Stub::async::SetObstacleInfo(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::ObstacleInfo* request, ::Nrmk::IndyFramework::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Nrmk::IndyFramework::ObstacleInfo, ::Nrmk::IndyFramework::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetObstacleInfo_, context, request, response, std::move(f));
}

void TeleOp::Stub::async::SetObstacleInfo(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::ObstacleInfo* request, ::Nrmk::IndyFramework::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetObstacleInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::Empty>* TeleOp::Stub::PrepareAsyncSetObstacleInfoRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::ObstacleInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::ObstacleInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetObstacleInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::Empty>* TeleOp::Stub::AsyncSetObstacleInfoRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::ObstacleInfo& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetObstacleInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TeleOp::Stub::GetObstacleInfo(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::ObstacleIndex& request, ::Nrmk::IndyFramework::ObstacleInfo* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Nrmk::IndyFramework::ObstacleIndex, ::Nrmk::IndyFramework::ObstacleInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetObstacleInfo_, context, request, response);
}

void TeleOp::Stub::async::GetObstacleInfo(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::ObstacleIndex* request, ::Nrmk::IndyFramework::ObstacleInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Nrmk::IndyFramework::ObstacleIndex, ::Nrmk::IndyFramework::ObstacleInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetObstacleInfo_, context, request, response, std::move(f));
}

void TeleOp::Stub::async::GetObstacleInfo(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::ObstacleIndex* request, ::Nrmk::IndyFramework::ObstacleInfo* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetObstacleInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::ObstacleInfo>* TeleOp::Stub::PrepareAsyncGetObstacleInfoRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::ObstacleIndex& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Nrmk::IndyFramework::ObstacleInfo, ::Nrmk::IndyFramework::ObstacleIndex, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetObstacleInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::ObstacleInfo>* TeleOp::Stub::AsyncGetObstacleInfoRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::ObstacleIndex& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetObstacleInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TeleOp::Stub::GetCollisionSpheres(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::Nrmk::IndyFramework::CollisionSpheresInfo* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::CollisionSpheresInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetCollisionSpheres_, context, request, response);
}

void TeleOp::Stub::async::GetCollisionSpheres(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::CollisionSpheresInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::CollisionSpheresInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetCollisionSpheres_, context, request, response, std::move(f));
}

void TeleOp::Stub::async::GetCollisionSpheres(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::CollisionSpheresInfo* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetCollisionSpheres_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::CollisionSpheresInfo>* TeleOp::Stub::PrepareAsyncGetCollisionSpheresRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Nrmk::IndyFramework::CollisionSpheresInfo, ::Nrmk::IndyFramework::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetCollisionSpheres_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::CollisionSpheresInfo>* TeleOp::Stub::AsyncGetCollisionSpheresRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetCollisionSpheresRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TeleOp::Stub::GetJointConstraintConfig(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::Nrmk::IndyFramework::JointConstraintConfig* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::JointConstraintConfig, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetJointConstraintConfig_, context, request, response);
}

void TeleOp::Stub::async::GetJointConstraintConfig(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::JointConstraintConfig* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::JointConstraintConfig, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetJointConstraintConfig_, context, request, response, std::move(f));
}

void TeleOp::Stub::async::GetJointConstraintConfig(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::JointConstraintConfig* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetJointConstraintConfig_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::JointConstraintConfig>* TeleOp::Stub::PrepareAsyncGetJointConstraintConfigRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Nrmk::IndyFramework::JointConstraintConfig, ::Nrmk::IndyFramework::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetJointConstraintConfig_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::JointConstraintConfig>* TeleOp::Stub::AsyncGetJointConstraintConfigRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetJointConstraintConfigRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TeleOp::Stub::GetSelfCollisionPairs(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::Nrmk::IndyFramework::SelfCollisionPairs* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::SelfCollisionPairs, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetSelfCollisionPairs_, context, request, response);
}

void TeleOp::Stub::async::GetSelfCollisionPairs(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::SelfCollisionPairs* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::SelfCollisionPairs, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSelfCollisionPairs_, context, request, response, std::move(f));
}

void TeleOp::Stub::async::GetSelfCollisionPairs(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::SelfCollisionPairs* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSelfCollisionPairs_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::SelfCollisionPairs>* TeleOp::Stub::PrepareAsyncGetSelfCollisionPairsRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Nrmk::IndyFramework::SelfCollisionPairs, ::Nrmk::IndyFramework::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetSelfCollisionPairs_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::SelfCollisionPairs>* TeleOp::Stub::AsyncGetSelfCollisionPairsRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetSelfCollisionPairsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TeleOp::Stub::GetPlaneConstraintConfig(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::Nrmk::IndyFramework::PlaneConstraintConfig* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::PlaneConstraintConfig, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetPlaneConstraintConfig_, context, request, response);
}

void TeleOp::Stub::async::GetPlaneConstraintConfig(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::PlaneConstraintConfig* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::PlaneConstraintConfig, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPlaneConstraintConfig_, context, request, response, std::move(f));
}

void TeleOp::Stub::async::GetPlaneConstraintConfig(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::PlaneConstraintConfig* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPlaneConstraintConfig_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::PlaneConstraintConfig>* TeleOp::Stub::PrepareAsyncGetPlaneConstraintConfigRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Nrmk::IndyFramework::PlaneConstraintConfig, ::Nrmk::IndyFramework::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetPlaneConstraintConfig_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::PlaneConstraintConfig>* TeleOp::Stub::AsyncGetPlaneConstraintConfigRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetPlaneConstraintConfigRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TeleOp::Stub::GetStaticObstacleConstraintConfig(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::Nrmk::IndyFramework::ObstacleConstraintConfig* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::ObstacleConstraintConfig, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetStaticObstacleConstraintConfig_, context, request, response);
}

void TeleOp::Stub::async::GetStaticObstacleConstraintConfig(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::ObstacleConstraintConfig* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::ObstacleConstraintConfig, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStaticObstacleConstraintConfig_, context, request, response, std::move(f));
}

void TeleOp::Stub::async::GetStaticObstacleConstraintConfig(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::ObstacleConstraintConfig* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStaticObstacleConstraintConfig_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::ObstacleConstraintConfig>* TeleOp::Stub::PrepareAsyncGetStaticObstacleConstraintConfigRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Nrmk::IndyFramework::ObstacleConstraintConfig, ::Nrmk::IndyFramework::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetStaticObstacleConstraintConfig_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::ObstacleConstraintConfig>* TeleOp::Stub::AsyncGetStaticObstacleConstraintConfigRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetStaticObstacleConstraintConfigRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TeleOp::Stub::GetDynamicObstacleConstraintConfig(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::Nrmk::IndyFramework::ObstacleConstraintConfig* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::ObstacleConstraintConfig, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetDynamicObstacleConstraintConfig_, context, request, response);
}

void TeleOp::Stub::async::GetDynamicObstacleConstraintConfig(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::ObstacleConstraintConfig* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::ObstacleConstraintConfig, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDynamicObstacleConstraintConfig_, context, request, response, std::move(f));
}

void TeleOp::Stub::async::GetDynamicObstacleConstraintConfig(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::ObstacleConstraintConfig* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDynamicObstacleConstraintConfig_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::ObstacleConstraintConfig>* TeleOp::Stub::PrepareAsyncGetDynamicObstacleConstraintConfigRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Nrmk::IndyFramework::ObstacleConstraintConfig, ::Nrmk::IndyFramework::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetDynamicObstacleConstraintConfig_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::ObstacleConstraintConfig>* TeleOp::Stub::AsyncGetDynamicObstacleConstraintConfigRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetDynamicObstacleConstraintConfigRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TeleOp::Stub::GetOrientationDeviationConfig(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::Nrmk::IndyFramework::OrientationDeviationConfig* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::OrientationDeviationConfig, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetOrientationDeviationConfig_, context, request, response);
}

void TeleOp::Stub::async::GetOrientationDeviationConfig(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::OrientationDeviationConfig* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::OrientationDeviationConfig, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetOrientationDeviationConfig_, context, request, response, std::move(f));
}

void TeleOp::Stub::async::GetOrientationDeviationConfig(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::OrientationDeviationConfig* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetOrientationDeviationConfig_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::OrientationDeviationConfig>* TeleOp::Stub::PrepareAsyncGetOrientationDeviationConfigRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Nrmk::IndyFramework::OrientationDeviationConfig, ::Nrmk::IndyFramework::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetOrientationDeviationConfig_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::OrientationDeviationConfig>* TeleOp::Stub::AsyncGetOrientationDeviationConfigRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetOrientationDeviationConfigRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TeleOp::Stub::GetDesiredPosition(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::Nrmk::IndyFramework::DesiredPosition* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::DesiredPosition, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetDesiredPosition_, context, request, response);
}

void TeleOp::Stub::async::GetDesiredPosition(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::DesiredPosition* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::DesiredPosition, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDesiredPosition_, context, request, response, std::move(f));
}

void TeleOp::Stub::async::GetDesiredPosition(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::DesiredPosition* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDesiredPosition_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::DesiredPosition>* TeleOp::Stub::PrepareAsyncGetDesiredPositionRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Nrmk::IndyFramework::DesiredPosition, ::Nrmk::IndyFramework::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetDesiredPosition_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::DesiredPosition>* TeleOp::Stub::AsyncGetDesiredPositionRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetDesiredPositionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TeleOp::Stub::GetCurrentPosition(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::Nrmk::IndyFramework::CurrentPosition* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::CurrentPosition, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetCurrentPosition_, context, request, response);
}

void TeleOp::Stub::async::GetCurrentPosition(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::CurrentPosition* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::CurrentPosition, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetCurrentPosition_, context, request, response, std::move(f));
}

void TeleOp::Stub::async::GetCurrentPosition(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::CurrentPosition* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetCurrentPosition_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::CurrentPosition>* TeleOp::Stub::PrepareAsyncGetCurrentPositionRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Nrmk::IndyFramework::CurrentPosition, ::Nrmk::IndyFramework::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetCurrentPosition_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Nrmk::IndyFramework::CurrentPosition>* TeleOp::Stub::AsyncGetCurrentPositionRaw(::grpc::ClientContext* context, const ::Nrmk::IndyFramework::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetCurrentPositionRaw(context, request, cq);
  result->StartCall();
  return result;
}

TeleOp::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TeleOp_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TeleOp::Service, ::Nrmk::IndyFramework::ObstacleInfo, ::Nrmk::IndyFramework::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TeleOp::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Nrmk::IndyFramework::ObstacleInfo* req,
             ::Nrmk::IndyFramework::Empty* resp) {
               return service->SetObstacleInfo(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TeleOp_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TeleOp::Service, ::Nrmk::IndyFramework::ObstacleIndex, ::Nrmk::IndyFramework::ObstacleInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TeleOp::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Nrmk::IndyFramework::ObstacleIndex* req,
             ::Nrmk::IndyFramework::ObstacleInfo* resp) {
               return service->GetObstacleInfo(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TeleOp_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TeleOp::Service, ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::CollisionSpheresInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TeleOp::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Nrmk::IndyFramework::Empty* req,
             ::Nrmk::IndyFramework::CollisionSpheresInfo* resp) {
               return service->GetCollisionSpheres(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TeleOp_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TeleOp::Service, ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::JointConstraintConfig, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TeleOp::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Nrmk::IndyFramework::Empty* req,
             ::Nrmk::IndyFramework::JointConstraintConfig* resp) {
               return service->GetJointConstraintConfig(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TeleOp_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TeleOp::Service, ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::SelfCollisionPairs, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TeleOp::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Nrmk::IndyFramework::Empty* req,
             ::Nrmk::IndyFramework::SelfCollisionPairs* resp) {
               return service->GetSelfCollisionPairs(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TeleOp_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TeleOp::Service, ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::PlaneConstraintConfig, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TeleOp::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Nrmk::IndyFramework::Empty* req,
             ::Nrmk::IndyFramework::PlaneConstraintConfig* resp) {
               return service->GetPlaneConstraintConfig(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TeleOp_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TeleOp::Service, ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::ObstacleConstraintConfig, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TeleOp::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Nrmk::IndyFramework::Empty* req,
             ::Nrmk::IndyFramework::ObstacleConstraintConfig* resp) {
               return service->GetStaticObstacleConstraintConfig(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TeleOp_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TeleOp::Service, ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::ObstacleConstraintConfig, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TeleOp::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Nrmk::IndyFramework::Empty* req,
             ::Nrmk::IndyFramework::ObstacleConstraintConfig* resp) {
               return service->GetDynamicObstacleConstraintConfig(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TeleOp_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TeleOp::Service, ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::OrientationDeviationConfig, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TeleOp::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Nrmk::IndyFramework::Empty* req,
             ::Nrmk::IndyFramework::OrientationDeviationConfig* resp) {
               return service->GetOrientationDeviationConfig(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TeleOp_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TeleOp::Service, ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::DesiredPosition, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TeleOp::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Nrmk::IndyFramework::Empty* req,
             ::Nrmk::IndyFramework::DesiredPosition* resp) {
               return service->GetDesiredPosition(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TeleOp_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TeleOp::Service, ::Nrmk::IndyFramework::Empty, ::Nrmk::IndyFramework::CurrentPosition, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TeleOp::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Nrmk::IndyFramework::Empty* req,
             ::Nrmk::IndyFramework::CurrentPosition* resp) {
               return service->GetCurrentPosition(ctx, req, resp);
             }, this)));
}

TeleOp::Service::~Service() {
}

::grpc::Status TeleOp::Service::SetObstacleInfo(::grpc::ServerContext* context, const ::Nrmk::IndyFramework::ObstacleInfo* request, ::Nrmk::IndyFramework::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TeleOp::Service::GetObstacleInfo(::grpc::ServerContext* context, const ::Nrmk::IndyFramework::ObstacleIndex* request, ::Nrmk::IndyFramework::ObstacleInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TeleOp::Service::GetCollisionSpheres(::grpc::ServerContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::CollisionSpheresInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TeleOp::Service::GetJointConstraintConfig(::grpc::ServerContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::JointConstraintConfig* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TeleOp::Service::GetSelfCollisionPairs(::grpc::ServerContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::SelfCollisionPairs* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TeleOp::Service::GetPlaneConstraintConfig(::grpc::ServerContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::PlaneConstraintConfig* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TeleOp::Service::GetStaticObstacleConstraintConfig(::grpc::ServerContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::ObstacleConstraintConfig* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TeleOp::Service::GetDynamicObstacleConstraintConfig(::grpc::ServerContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::ObstacleConstraintConfig* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TeleOp::Service::GetOrientationDeviationConfig(::grpc::ServerContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::OrientationDeviationConfig* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TeleOp::Service::GetDesiredPosition(::grpc::ServerContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::DesiredPosition* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TeleOp::Service::GetCurrentPosition(::grpc::ServerContext* context, const ::Nrmk::IndyFramework::Empty* request, ::Nrmk::IndyFramework::CurrentPosition* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Nrmk
}  // namespace IndyFramework

