# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mimic.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import mimic_msgs_pb2 as mimic__msgs__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mimic.proto',
  package='IndyFramework.Protobuf.MimicServer',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bmimic.proto\x12\"IndyFramework.Protobuf.MimicServer\x1a\x10mimic_msgs.proto2\xbf\x04\n\tMoveMimic\x12n\n\x0fSetRobotAddress\x12+.IndyFramework.Protobuf.MimicServer.Address\x1a,.IndyFramework.Protobuf.MimicServer.Response\"\x00\x12o\n\x0cGetSkillList\x12).IndyFramework.Protobuf.MimicServer.Empty\x1a\x32.IndyFramework.Protobuf.MimicServer.MimicSkillList\"\x00\x12y\n\x0cGetSkillHome\x12\x32.IndyFramework.Protobuf.MimicServer.MimicSkillName\x1a\x33.IndyFramework.Protobuf.MimicServer.GetSkillHomeRes\"\x00\x12n\n\x08RunSkill\x12\x32.IndyFramework.Protobuf.MimicServer.MimicSkillName\x1a,.IndyFramework.Protobuf.MimicServer.Response\"\x00\x12\x66\n\tStopSkill\x12).IndyFramework.Protobuf.MimicServer.Empty\x1a,.IndyFramework.Protobuf.MimicServer.Response\"\x00\x62\x06proto3'
  ,
  dependencies=[mimic__msgs__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_MOVEMIMIC = _descriptor.ServiceDescriptor(
  name='MoveMimic',
  full_name='IndyFramework.Protobuf.MimicServer.MoveMimic',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=70,
  serialized_end=645,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetRobotAddress',
    full_name='IndyFramework.Protobuf.MimicServer.MoveMimic.SetRobotAddress',
    index=0,
    containing_service=None,
    input_type=mimic__msgs__pb2._ADDRESS,
    output_type=mimic__msgs__pb2._RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetSkillList',
    full_name='IndyFramework.Protobuf.MimicServer.MoveMimic.GetSkillList',
    index=1,
    containing_service=None,
    input_type=mimic__msgs__pb2._EMPTY,
    output_type=mimic__msgs__pb2._MIMICSKILLLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetSkillHome',
    full_name='IndyFramework.Protobuf.MimicServer.MoveMimic.GetSkillHome',
    index=2,
    containing_service=None,
    input_type=mimic__msgs__pb2._MIMICSKILLNAME,
    output_type=mimic__msgs__pb2._GETSKILLHOMERES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RunSkill',
    full_name='IndyFramework.Protobuf.MimicServer.MoveMimic.RunSkill',
    index=3,
    containing_service=None,
    input_type=mimic__msgs__pb2._MIMICSKILLNAME,
    output_type=mimic__msgs__pb2._RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StopSkill',
    full_name='IndyFramework.Protobuf.MimicServer.MoveMimic.StopSkill',
    index=4,
    containing_service=None,
    input_type=mimic__msgs__pb2._EMPTY,
    output_type=mimic__msgs__pb2._RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MOVEMIMIC)

DESCRIPTOR.services_by_name['MoveMimic'] = _MOVEMIMIC

# @@protoc_insertion_point(module_scope)
