# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mimic_msgs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10mimic_msgs.proto\x12\"IndyFramework.Protobuf.MimicServer\"\x07\n\x05\x45mpty\"%\n\x08Response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x03\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x1e\n\x0eMimicSkillName\x12\x0c\n\x04name\x18\x01 \x01(\t\"$\n\x0eMimicSkillList\x12\x12\n\nskill_list\x18\x01 \x03(\t\"\x1f\n\x0fGetSkillHomeRes\x12\x0c\n\x04jpos\x18\x02 \x03(\x02\"#\n\x07\x41\x64\x64ress\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\"5\n\x0bMimicServer\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mimic_msgs_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=56
  _globals['_EMPTY']._serialized_end=63
  _globals['_RESPONSE']._serialized_start=65
  _globals['_RESPONSE']._serialized_end=102
  _globals['_MIMICSKILLNAME']._serialized_start=104
  _globals['_MIMICSKILLNAME']._serialized_end=134
  _globals['_MIMICSKILLLIST']._serialized_start=136
  _globals['_MIMICSKILLLIST']._serialized_end=172
  _globals['_GETSKILLHOMERES']._serialized_start=174
  _globals['_GETSKILLHOMERES']._serialized_end=205
  _globals['_ADDRESS']._serialized_start=207
  _globals['_ADDRESS']._serialized_end=242
  _globals['_MIMICSERVER']._serialized_start=244
  _globals['_MIMICSERVER']._serialized_end=297
# @@protoc_insertion_point(module_scope)
